//Name|Class|CR|Type|Terrain|Book/Page|isUnique
// 0 	== 1/2 CR
// -1 	== 1/3 CR
// -2	== 1/4 CR
// -3	== 1/6 CR
// -4	== 1/8 CR

var bestiary4 = [
['Abaia','','10','magical beast','lakes','Bestiary 4',false],
['Almiraj','','1','magical beast','hills,plains,forests','Bestiary 4',false],
['Alpluachra','','0','fey','forests,lakes,rivers','Bestiary 4',false],
['Ankou','','14','fey','lands','Bestiary 4',false],
['Aoandon','','12','outsider','any','Bestiary 4',false],
['Apocalypse Locust','','6','outsider','Abyss,Hell,Abaddon','Bestiary 4',false],
['Archaeopteryx','','-2','animal','forests','Bestiary 4',false],
['Argus','','13','aberration','lands','Bestiary 4',false],
['Astral Leviathan','','18','outsider','Extraplanar','Bestiary 4',false],
['Bakekujira','','17','undead','oceans','Bestiary 4',false],
['Barometz','','15','plant','forests','Bestiary 4',false],
['Beheaded','','-1','undead','any','Bestiary 4',false],
['Bhole','','17','magical beast','underground','Bestiary 4',false],
['Bodythief','','14','plant','forests','Bestiary 4',false],
['Boilborn','','1','ooze','any','Bestiary 4',false],
['Brethedan','','5','aberration','air','Bestiary 4',false],
['Broken Soul Lillend','','9','outsider','any','Bestiary 4',false],
['Buggane','','5','monstrous humanoid','underground','Bestiary 4',false],
['Cephalophore','','8','construct','any','Bestiary 4',false],
['Chaneque','','1','fey','forests','Bestiary 4',false],
['Changeling','witch 1','0','humanoid','any','Bestiary 4',false],
['Clockwork Dragon','','16','construct','lands','Bestiary 4',false],
['Clockwork Mage','','9','construct','lands','Bestiary 4',false],
['Clockwork Steed','','6','construct','lands','Bestiary 4',false],
['Flesh Colossus','','16','construct','lands','Bestiary 4',false],
['Iron Colossus','','21','construct','lands','Bestiary 4',false],
['Stone Colossus','','19','construct','lands','Bestiary 4',false],
['Colour Out Of Space','','10','ooze','any','Bestiary 4',false],
['Comozant Wyrd','','4','outsider','oceans','Bestiary 4',false],
['Contemplative','','2','monstrous humanoid','urban','Bestiary 4',false],
['Dark Caller','','5','humanoid','underground','Bestiary 4',false],
['Dark Dancer','','1','humanoid','underground','Bestiary 4',false],
['Death Dog','','2','magical beast','deserts','Bestiary 4',false],
['Dagon','','27','outsider','Abyss','Bestiary 4',true],
['Kostchtchie','','23','outsider','Abyss','Bestiary 4',true],
['Pazuzu','','28','outsider','Abyss','Bestiary 4',true],
['Drowning Devil','','8','outsider','Hell','Bestiary 4',false],
['Host Devil','','6','outsider','Hell','Bestiary 4',false],
['Nemesis Devil','','18','outsider','Hell','Bestiary 4',false],
['Dimorphodon','','1','animal','coastlines,forests','Bestiary 4',false],
['Diplodocus','','12','animal','plains','Bestiary 4',false],
['Styracosaurus','','5','animal','plains','Bestiary 4',false],
['Velociraptor','','2','animal','forests,plains','Bestiary 4',false],
['Dodo','','-2','animal','coastlines','Bestiary 4',false],
['Dorvae','','11','outsider','Hell,Abyss,Abaddon','Bestiary 4',false],
['Dossenus','','1','aberration','underground','Bestiary 4',false],
['Adult Lunar Dragon','','13','dragon','vacuum','Bestiary 4',false],
['Ancient Lunar Dragon','','18','dragon','vacuum','Bestiary 4',false],
['Young Lunar Dragon','','9','dragon','vacuum','Bestiary 4',false],
['Adult Solar Dragon','','13','dragon','vacuum','Bestiary 4',false],
['Ancient Solar Dragon','','18','dragon','vacuum','Bestiary 4',false],
['Young Solar Dragon','','9','dragon','vacuum','Bestiary 4',false],
['Adult Time Dragon','','15','dragon','vacuum','Bestiary 4',false],
['Ancient Time Dragon','','20','dragon','vacuum','Bestiary 4',false],
['Young Time Dragon','','11','dragon','vacuum','Bestiary 4',false],
['Adult Void Dragon','','13','dragon','vacuum','Bestiary 4',false],
['Ancient Void Dragon','','18','dragon','vacuum','Bestiary 4',false],
['Young Void Dragon','','9','dragon','vacuum','Bestiary 4',false],
['Adult Vortex Dragon','','14','dragon','vacuum','Bestiary 4',false],
['Ancient Vortex Dragon','','19','dragon','vacuum','Bestiary 4',false],
['Young Vortex Dragon','','10','dragon','vacuum','Bestiary 4',false],
['Drakainia','','25','aberration','any','Bestiary 4',false],
['Lava Drake','','9','dragon','forests,mountains,hills','Bestiary 4',false],
['Mist Drake','','5','dragon','cold,coastlines,hills,marshes','Bestiary 4',false],
['Shadow Drake','','2','dragon','any','Bestiary 4',false],
['Spire Drake','','7','dragon','hills','Bestiary 4',false],
['Ectoplasmic Human','','0','undead','any','Bestiary 4',false],
['Einherji','','10','outsider','any','Bestiary 4',false],
['Elder Thing','','5','aberration','any','Bestiary 4',false],
['Elohim','','23','outsider','extraplanar,Extraplanar','Bestiary 4',false],
['Cernunnos','','30','outsider','forests,plains,Elysium','Bestiary 4',true],
['Korada','','26','outsider','forests,mountains,Nirvana','Bestiary 4',true],
['Vildeis','','28','outsider','Heaven','Bestiary 4',true],
['Erlking','','18','fey','forests','Bestiary 4',false],
['Fachen','','5','aberration','hills,plains','Bestiary 4',false],
['Festering Spirit','','8','undead','underground,lands','Bestiary 4',false],
['Mammoth Flea','','2','vermin','forests,hills,mountains,plains','Bestiary 4',false],
['Giant Flea','','0','vermin','lands,underground','Bestiary 4',false],
['Fleshdreg','','1','aberration','ruins','Bestiary 4',false],
['Ghonhatine','','10','aberration','underground','Bestiary 4',false],
['Grothlut','','3','aberration','underground','Bestiary 4',false],
['Halsora','','7','aberration','underground','Bestiary 4',false],
['Irnakurse','','9','aberration','underground','Bestiary 4',false],
['Flying Polyp','','14','aberration','any','Bestiary 4',false],
['Formian Myrmarch','','10','monstrous humanoid','underground,lands','Bestiary 4',false],
['Formian Queen','','17','monstrous humanoid','underground,lands','Bestiary 4',false],
['Formian Taskmaster','','7','monstrous humanoid','underground,lands','Bestiary 4',false],
['Formian Warrior','','3','monstrous humanoid','underground,lands','Bestiary 4',false],
['Formian Worker','','0','monstrous humanoid','underground,lands','Bestiary 4',false],
['Fossegrim','','4','fey','cold,lakes,rivers','Bestiary 4',false],
['Freezing Flow','','4','ooze','cold,any','Bestiary 4',false],
['Fungal Nymph','','8','plant','ruins,underground','Bestiary 4',false],
['Gaki','','7','undead','lands','Bestiary 4',false],
['Gallowdead','','16','undead','any','Bestiary 4',false],
['Galvo','','9','magical beast','oceans,coastlines','Bestiary 4',false],
['Gashadokuro','','13','undead','any','Bestiary 4',false],
['Gathlain','sorcerer 1','0','fey','jungles,forests','Bestiary 4',false],
['Gearghost','','5','undead','urban,underground','Bestiary 4',false],
['Geist','','9','undead','ruins','Bestiary 4',false],
['Gholdako','','10','undead','coastlines','Bestiary 4',false],
['Cliff Giant','','9','humanoid','plains,deserts','Bestiary 4',false],
['oceans Giant','','14','humanoid','oceans','Bestiary 4',false],
['River Giant','','6','humanoid','rivers','Bestiary 4',false],
['Slag Giant','','7','humanoid','mountains,underground','Bestiary 4',false],
['Blood Golem','','5','aberration','any','Bestiary 4',false],
['Coral Golem','','9','construct','coastlines,oceans','Bestiary 4',false],
['Junk Golem','','4','construct','any','Bestiary 4',false],
['Wax Golem','','3','construct','any','Bestiary 4',false],
['Graeae','','5','monstrous humanoid','any','Bestiary 4',false],
['Bokrug','','27','magical beast','lakes,rivers,oceans,swamps','Bestiary 4',true],
['Cthulhu','','30','aberration','any,Extraplanar','Bestiary 4',true],
['Hastur','','29','aberration','any','Bestiary 4',true],
['Grimple','','-1','fey','urban','Bestiary 4',false],
['Haniver','','0','fey','coastlines','Bestiary 4',false],
['Monaciello','','1','fey','urban','Bestiary 4',false],
['Grendel','','19','monstrous humanoid','cold,swamps','Bestiary 4',false],
['Guardian Dragon','','24','dragon','any','Bestiary 4',false],
['Blood Hag','','8','monstrous humanoid','lands','Bestiary 4',false],
['Winter Hag','','7','monstrous humanoid','cold,plains,forests','Bestiary 4',false],
['Hamadryad','','15','fey','forests','Bestiary 4',false],
['Harionago','','11','undead','lands','Bestiary 4',false],
['Giraffe','','3','animal','plains','Bestiary 4',false],
['Stag','','1','animal','lands','Bestiary 4',false],
['Huldra','','4','fey','cold,forests','Bestiary 4',false],
['Hungry Flesh','','3','ooze','lands,underground','Bestiary 4',false],
['Hyakume','','15','aberration','underground','Bestiary 4',false],
['Hypnalis','','5','outsider','Ethereal Plane','Bestiary 4',false],
['Ijiraq','','9','fey','cold,plains,forests','Bestiary 4',false],
['Immortal Ichor','','17','ooze','ruins','Bestiary 4',false],
['Incutilis','','2','aberration','oceans','Bestiary 4',false],
['Irminsul','','17','plant','any','Bestiary 4',false],
['Isitoq','','0','undead','any','Bestiary 4',false],
['Jack-O\'-Lantern','','1','plant','forests,hills,plains','Bestiary 4',false],
['Jinmenju','','11','plant','hills,mountains','Bestiary 4',false],
['Juggernaut','','11','construct','any','Bestiary 4',false],
['Julunggali','','21','magical beast','lands,rivers,lakes','Bestiary 4',false],
['Agyra','','27','magical beast','mountains','Bestiary 4',true],
['Bezravnis','','26','magical beast','deserts','Bestiary 4',true],
['Mogaru','','28','magical beast','forests,lakes,oceans','Bestiary 4',true],
['Kapre','','2','fey','forests','Bestiary 4',false],
['Karkinoi','','6','monstrous humanoid','oceans,coastlines,rivers','Bestiary 4',false],
['Kasatha','monk 1','0','humanoid','deserts','Bestiary 4',false],
['Kitsune','sorcerer 1','0','humanoid','forests,hills,mountains','Bestiary 4',false],
['Ostiarius','','5','outsider','Plane of Shadow','Bestiary 4',false],
['Sacristan','','10','outsider','Plane of Shadow','Bestiary 4',false],
['Lampad','','5','fey','underground','Bestiary 4',false],
['Leaf Ray','','1','plant','forests','Bestiary 4',false],
['Leanan Sidhe','','9','fey','lands','Bestiary 4',false],
['Living Topiary','','4','plant','lands','Bestiary 4',false],
['Living Wall','','4','construct','ruins,underground','Bestiary 4',false],
['Locust Swarm','','2','vermin','deserts,plains','Bestiary 4',false],
['Giant Locust','','3','vermin','deserts,plains','Bestiary 4',false],
['Lorelei','','12','aberration','coastlines','Bestiary 4',false],
['Lunarma','','6','aberration','underground','Bestiary 4',false],
['Executioner\'s Hood','','2','aberration','underground','Bestiary 4',false],
['Lurker Above','','7','aberration','underground','Bestiary 4',false],
['Trapper','','8','aberration','underground','Bestiary 4',false],
['Werebat','','3','humanoid','forests,hills','Bestiary 4',false],
['Werecrocodile','','3','humanoid','rivers,marshes','Bestiary 4',false],
['Wereshark','fighter 3','3','humanoid','oceans,coastlines','Bestiary 4',false],
['Maenad','','8','monstrous humanoid','forests,plains','Bestiary 4',false],
['Manitou','','15','outsider','plains,forests','Bestiary 4',false],
['Mi-Go','','6','plant','any','Bestiary 4',false],
['Mindslaver Mold','','3','plant','any','Bestiary 4',false],
['Mudlord','','6','outsider','marshes,underground','Bestiary 4',false],
['Mummified Gynosphinx','','9','undead','ruins','Bestiary 4',false],
['Myrmecoleon','','10','magical beast','plains,hills','Bestiary 4',false],
['Nagaji','fighter 1','0','humanoid','forests,hills','Bestiary 4',false],
['Necrocraft','','3','undead','lands,underground','Bestiary 4',false],
['Nependis','','9','monstrous humanoid','forests','Bestiary 4',false],
['Nightgaunt','','4','monstrous humanoid','mountains,Extraplanar','Bestiary 4',false],
['Nightmare Ettercap','','4','aberration','forests','Bestiary 4',false],
['Ningyo','','1','monstrous humanoid','oceans','Bestiary 4',false],
['Nycar','','2','dragon','cold,marshes','Bestiary 4',false],
['Oceanid','','7','fey','oceans','Bestiary 4',false],
['Oma','','16','magical beast','vacuum','Bestiary 4',false],
['Owb','','6','outsider','lands,underground,Plane of Shadow','Bestiary 4',false],
['Pard','','3','magical beast','forests,plains','Bestiary 4',false],
['Peluda','','10','dragon','marshes,plains','Bestiary 4',false],
['Guardian Phantom Armor','','2','undead','any','Bestiary 4',false],
['Giant Phantom Armor','','4','undead','any','Bestiary 4',false],
['Pickled Punk','','1','undead','any','Bestiary 4',false],
['Pipefox','','2','magical beast','any','Bestiary 4',false],
['Platypus','','-3','animal','rivers','Bestiary 4',false],
['Pod-Spawned Guard Captain','fighter 9','8','plant','any','Bestiary 4',false],
['Pooka','','2','fey','any','Bestiary 4',false],
['Catrina','','5','outsider','Extraplanar','Bestiary 4',false],
['Morrigna','','13','outsider','Extraplanar','Bestiary 4',false],
['Nosoi','','2','outsider','Extraplanar','Bestiary 4',false],
['Vanth','','7','outsider','Extraplanar','Bestiary 4',false],
['Yamaraj','','20','outsider','Extraplanar','Bestiary 4',false],
['Qallupilluk','','7','monstrous humanoid','cold,oceans','Bestiary 4',false],
['Rat King','','5','magical beast','urban,underground','Bestiary 4',false],
['Ratling','','2','magical beast','urban','Bestiary 4',false],
['Rokurokubi','','14','monstrous humanoid','ruins','Bestiary 4',false],
['Rukh','','10','magical beast','deserts,mountains','Bestiary 4',false],
['Juvenile Rukh','','3','magical beast','mountains,deserts','Bestiary 4',false],
['Saguaroi','','5','plant','deserts','Bestiary 4',false],
['Samsaran','oracle 1','0','humanoid','lands','Bestiary 4',false],
['Sayona','','12','undead','lands,underground','Bestiary 4',false],
['Giant Emperor Scorpion','','11','vermin','deserts','Bestiary 4',false],
['Sea Cat','','4','magical beast','coastlines','Bestiary 4',false],
['Giant Seahorse','','2','animal','oceans,coastlines','Bestiary 4',false],
['Killer Seahorse','','5','animal','oceans','Bestiary 4',false],
['Seaweed Siren','','13','magical beast','coastlines','Bestiary 4',false],
['Selkie','','5','monstrous humanoid','cold,oceans','Bestiary 4',false],
['Seps','','11','magical beast','deserts,forests','Bestiary 4',false],
['Juvenile Seps','','2','magical beast','deserts,forests','Bestiary 4',false],
['Shadow Roper','','13','outsider','underground','Bestiary 4',false],
['Shard Slag','','8','ooze','underground','Bestiary 4',false],
['Bull Shark','','2','animal','oceans','Bestiary 4',false],
['Great White Shark','','4','animal','oceans','Bestiary 4',false],
['Shobhad','','4','monstrous humanoid','cold,deserts,mountains','Bestiary 4',false],
['Shredskin','','2','undead','lands','Bestiary 4',false],
['Shriezyx','','4','aberration','any','Bestiary 4',false],
['Shulsaga','','3','outsider','Extraplanar','Bestiary 4',false],
['Skinstitch','','5','construct','lands','Bestiary 4',false],
['Sloth','','-3','animal','forests','Bestiary 4',false],
['Snallygaster','','3','aberration','forests,mountains','Bestiary 4',false],
['Soulbound Mannequin','','7','construct','lands','Bestiary 4',false],
['Soulbound Shell','','12','construct','lands','Bestiary 4',false],
['Soulsliver','','2','outsider','lands,extraplanar','Bestiary 4',false],
['Spawn Of Yog-Sothoth','','10','aberration','hills','Bestiary 4',false],
['Goliath Spider','','11','vermin','forests,swamps','Bestiary 4',false],
['Scarlet Spider','','-2','vermin','any','Bestiary 4',false],
['Spring-Heeled Jack','','3','fey','lands','Bestiary 4',false],
['Star-Spawn Of Cthulhu','','20','aberration','any','Bestiary 4',false],
['Svartalfar','','8','fey','Plane of Shadow','Bestiary 4',false],
['Swan Maiden','','6','fey','lakes,swamps','Bestiary 4',false],
['Taniniver','','18','dragon','lands,underground','Bestiary 4',false],
['Tiberolith','','10','construct','coastlines,ruins,oceans,lakes','Bestiary 4',false],
['Tikbalang','','9','monstrous humanoid','jungles,jungles,forests','Bestiary 4',false],
['Fomorian Titan','','22','outsider','Abyss','Bestiary 4',false],
['Tooth Fairy','','-2','fey','urban,plains','Bestiary 4',false],
['Giant Tortoise','','1','animal','deserts,coastlines','Bestiary 4',false],
['Immense Tortoise','','8','animal','coastlines','Bestiary 4',false],
['Trox','barbarian 1','2','monstrous humanoid','jungles,deserts','Bestiary 4',false],
['Tuatara','','-2','animal','coastlines','Bestiary 4',false],
['Tunche','','17','fey','forests','Bestiary 4',false],
['Tyrant Jelly','','9','ooze','underground','Bestiary 4',false],
['Udaeus','','4','humanoid','lands,urban','Bestiary 4',false],
['Nosferatu','rogue 9','10','undead','urban,ruins','Bestiary 4',false],
['Vouivre','','12','monstrous humanoid','forests,lakes,rivers','Bestiary 4',false],
['Walrus','','3','animal','oceans,cold','Bestiary 4',false],
['Emperor Walrus','','8','animal','oceans,cold','Bestiary 4',false],
['Warsworn','','16','undead','any','Bestiary 4',false],
['Giant Water Strider','','1','vermin','lakes,rivers,swamps','Bestiary 4',false],
['Nymph Water Strider','','-2','vermin','lakes,rivers,swamps','Bestiary 4',false],
['Wayang','illusionist 1','0','humanoid','forests','Bestiary 4',false],
['Dire Weasel','','3','animal','lands','Bestiary 4',false],
['Giant Weasel','','1','animal','lands','Bestiary 4',false],
['Weedwhip','','2','plant','forests','Bestiary 4',false],
['Wickerman','','13','construct','lands','Bestiary 4',false],
['Wikkawak','','4','humanoid','cold,mountains','Bestiary 4',false],
['Wyrwood','rogue 1','0','construct','ruins,underground','Bestiary 4',false],
['Wyvaran','inquisitor 1','0','dragon','mountains','Bestiary 4',false],
['Xenopterid','','7','vermin','lands,underground','Bestiary 4',false],
['Yaoguai','','7','magical beast','lands','Bestiary 4',false],
['Ypotryll','','15','magical beast','marshes,hills,coastlines','Bestiary 4',false],
['Zombie Lord','monk 3','3','undead','any','Bestiary 4',false],
['Zomok','','16','plant','lands','Bestiary 4',false]
];