//Name|Class|CR|Type|Terrain|Book/Page|isUnique
// 0 	== 1/2 CR
// -1 	== 1/3 CR
// -2	== 1/4 CR
// -3	== 1/6 CR
// -4	== 1/8 CR

var bestiary5 = [
['Aatheriexa','','7','aberration','lands','Bestiary 5',false],
['Lipika Aeon','','18','outsider','any,extraplanar','Bestiary 5',false],
['Othas Aeon','','5','outsider','any,extraplanar','Bestiary 5',false],
['Aerial Servant','','11','outsider','any','Bestiary 5',false],
['Cervinal Agathion','','17','outsider','lands,Nirvana','Bestiary 5',false],
['Reptial Agathion','','4','outsider','lands,Nirvana','Bestiary 5',false],
['Ahkhat','','4','outsider','urban','Bestiary 5',false],
['Ahool','','9','magical beast','forests,ruins','Bestiary 5',false],
['Akaname','','1','aberration','urban,underground','Bestiary 5',false],
['Amarok','','12','magical beast','cold,forests,plains','Bestiary 5',false],
['Amphiptere','','4','dragon','deserts,hills,mountains','Bestiary 5',false],
['Android','rogue 1','1','humanoid','any','Bestiary 5',false],
['Anemos','','18','outsider','air','Bestiary 5',false],
['Balisse Angel','','8','outsider','Extraplanar','Bestiary 5',false],
['Choral Angel','','6','outsider','Extraplanar','Bestiary 5',false],
['Empyrean Angel','','20','outsider','Extraplanar','Bestiary 5',false],
['Balisse Angel','','8','outsider','Extraplanar','Bestiary 5',false],
['Animate Hair','','0','ooze','urban','Bestiary 5',false],
['Knight Ant','','4','vermin','any','Bestiary 5',false],
['Megapon Ant','','6','vermin','plains','Bestiary 5',false],
['Anunnaki','','18','monstrous humanoid','any','Bestiary 5',false],
['Apallie','','2','ooze','any','Bestiary 5',false],
['Megaprimatus Ape','','8','animal','forests,hills,mountains','Bestiary 5',false],
['Apkallu','','23','outsider','any','Bestiary 5',false],
['Exscinder Archon','','12','outsider','Heaven,any','Bestiary 5',false],
['Gate Archon','','17','outsider','Heaven,any','Bestiary 5',false],
['Giant Assassin Bug','','3','vermin','any','Bestiary 5',false],
['Great Assassin Bug','','5','vermin','any','Bestiary 5',false],
['Astomoi','psychic 1','0','humanoid','any,lands','Bestiary 5',false],
['Gancanagh Azata','','4','outsider','any,Elysium','Bestiary 5',false],
['Raelis Azata','','10','outsider','any,Elysium','Bestiary 5',false],
['Bagiennik','','6','fey','rivers','Bestiary 5',false],
['Polar Bear','','5','animal','coastlines,plains','Bestiary 5',false],
['Dire Polar Bear','','8','animal','coastlines,plains','Bestiary 5',false],
['Bisha Ga Tsuku','','9','outsider','hills,mountains','Bestiary 5',false],
['Blightspawn','','5','aberration','swamps','Bestiary 5',false],
['Bone Ship','','18','undead','oceans','Bestiary 5',false],
['Brain Mole','','1','magical beast','forests,hills,plains','Bestiary 5',false],
['Brain Mole Monarch','','5','magical beast','forests,hills,plains','Bestiary 5',false],
['Caller in Darkness','','9','undead','any','Bestiary 5',false],
['Cameroceras','','11','animal','oceans','Bestiary 5',false],['Capramace','','7','aberration','plains','Bestiary 5',false],
['Blood Caterpillar','','4','vermin','forests','Bestiary 5',false],
['Celedon','','1','construct','any','Bestiary 5',false],
['Ceratosaurus','','5','animal','forests,plains','Bestiary 5',false],
['Cerynitis','','7','magical beast','plains,hills,forests','Bestiary 5',false],
['Cetus','','13','dragon','oceans','Bestiary 5',false],
['Chalicotherium','','6','animal','forests','Bestiary 5',false],
['Cherufe','','13','magical beast','mountains','Bestiary 5',false],
['Chicken','','-3','animal','any,lands','Bestiary 5',false],
['Chuspiki','','2','magical beast','hills,mountains','Bestiary 5',false],
['Clockwork Familiar','','2','construct','any','Bestiary 5',false],
['Corpse Lotus','','13','plant','forests,marshes','Bestiary 5',false],
['Crone Queen','','15','undead','ruins','Bestiary 5',false],
['Crystal Golem','','11','construct','any','Bestiary 5',false],
['Cuero','','5','aberration','lakes,rivers','Bestiary 5',false],
['Cursed King','','10','undead','ruins','Bestiary 5',false],
['Cytillipede','','6','magical beast','underground','Bestiary 5',false],
['Caligni Dark Folk','rogue 1','0','humanoid','underground','Bestiary 5',false],
['Danava Titan','','24','outsider','any','Bestiary 5',false],
['Death Coach','','14','undead','any','Bestiary 5',false],
['Deep Merfolk','','3','humanoid','oceans','Bestiary 5',false],
['Deep One','','1','monstrous humanoid','Rivers,Lakes,Oceans','Bestiary 5',false],
['Elder Deep One','','14','monstrous humanoid','Rivers,Lakes,Oceans','Bestiary 5',false],
['Deep One Hybrid','cleric 1','0','humanoid','urban','Bestiary 5',false],
['Delgeth','','6','magical beast','forests','Bestiary 5',false],
['Abrikandilu Demon','','3','outsider','any,Abyss','Bestiary 5',false],
['Cambion Demon','','2','outsider','any,Abyss','Bestiary 5',false],
['Devastator','','22','construct','any,Abyss','Bestiary 5',false],
['Apostate Devil','','17','outsider','any,Hell','Bestiary 5',false],
['Digmaul','','3','animal','forests','Bestiary 5',false],
['Domovoi House Spirit','','3','fey','any,lands','Bestiary 5',false],
['Doppeldrek','','5','ooze','any','Bestiary 5',false],
['Dragonkin','','9','dragon','mountains','Bestiary 5',false],
['Young Astral Esoteric Dragon','','9','dragon','Extraplanar','Bestiary 5',false],
['Adult Astral Esoteric Dragon','','13','dragon','Extraplanar','Bestiary 5',false],
['Ancient Astral Esoteric Dragon','','18','dragon','Extraplanar','Bestiary 5',false],
['Young Dream Esoteric Dragon','','10','dragon','Extraplanar','Bestiary 5',false],
['Adult Dream Esoteric Dragon','','14','dragon','Extraplanar','Bestiary 5',false],
['Ancient Dream Esoteric Dragon','','19','dragon','Extraplanar','Bestiary 5',false],
['Young Etheric Esoteric Dragon','','7','dragon','Ethereal Plane','Bestiary 5',false],
['Adult Etheric Esoteric Dragon','','11','dragon','Ethereal Plane','Bestiary 5',false],
['Ancient Etheric Esoteric Dragon','','16','dragon','Ethereal Plane','Bestiary 5',false],
['Young Nightmare Esoteric Dragon','','6','dragon','Extraplanar','Bestiary 5',false],
['Adult Nightmare Esoteric Dragon','','10','dragon','Extraplanar','Bestiary 5',false],
['Ancient Nightmare Esoteric Dragon','','15','dragon','Extraplanar','Bestiary 5',false],
['Young Occult Esoteric Dragon','','6','dragon','any','Bestiary 5',false],
['Adult Occult Esoteric Dragon','','10','dragon','any','Bestiary 5',false],
['Ancient Occult Esoteric Dragon','','15','dragon','any','Bestiary 5',false],
['Duppy','','7','undead','coastlines','Bestiary 5',false],
['Dvorovoi House Spirit','','4','fey','any,lands','Bestiary 5',false],
['Dwiergeth','','13','aberration','mountains','Bestiary 5',false],
['Air Veela','','7','outsider','hills,mountains','Bestiary 5',false],
['Air Wysp','','2','outsider','Plane of Air,Ethereal Plane','Bestiary 5',false],
['Earth Veela','','7','outsider','mountains,underground','Bestiary 5',false],
['Earth Wysp','','2','outsider','Plane of Earth,Ethereal Plane','Bestiary 5',false],
['Echeneis','','1','magical beast','Rivers,Lakes,Oceans','Bestiary 5',false],
['Small Aether Elemental','','1','outsider','any,Ethereal Plane','Bestiary 5',false],
['Medium Aether Elemental','','3','outsider','any,Ethereal Plane','Bestiary 5',false],
['Large Aether Elemental','','5','outsider','any,Ethereal Plane','Bestiary 5',false],
['Huge Aether Elemental','','7','outsider','any,Ethereal Plane','Bestiary 5',false],
['Greater Aether Elemental','','9','outsider','any,Ethereal Plane','Bestiary 5',false],
['Elder Aether Elemental','','11','outsider','any,Ethereal Plane','Bestiary 5',false],
['Eclipse Giant','','19','humanoid','plains','Bestiary 5',false],
['Egregore','','10','aberration','any','Bestiary 5',false],
['Emotion Ooze','','6','ooze','any','Bestiary 5',false],
['Encantado','','8','fey','rivers','Bestiary 5',false],
['Esipil Sahkil','','2','outsider','any,Ethereal Plane','Bestiary 5',false],
['Ether Drake','','10','dragon','any','Bestiary 5',false],
['Etiainen','','1','outsider','urban','Bestiary 5',false],
['Fastachee','','11','fey','any,lands','Bestiary 5',false],
['Fext','','10','undead','any','Bestiary 5',false],
['Firbolg','','4','humanoid','hills,forests','Bestiary 5',false],
['Fire Veela','','7','outsider','any,lands,Plane of Fire','Bestiary 5',false],
['Fire Wysp','','2','outsider','Plane of Fire,Ethereal Plane','Bestiary 5',false],
['Flying Fox','','-1','animal','forests','Bestiary 5',false],
['Flytrap Leshy','','4','plant','marshes,swamps','Bestiary 5',false],
['Frog Father','','5','animal','marshes,Rivers,Lakes,Oceans','Bestiary 5',false],
['Gearsman Robot','','4','construct','any','Bestiary 5',false],
['Gegenees','','16','monstrous humanoid','any,lands','Bestiary 5',false],
['Ghoran','bard 1','1','plant','any','Bestiary 5',false],
['Giant Mantis Shrimp','','9','vermin','coastlines','Bestiary 5',false],
['Giant Muckdweller','','2','magical beast','marshes','Bestiary 5',false],
['Giant Scarab','','6','vermin','deserts','Bestiary 5',false],
['Giant Termite','','3','vermin','forests,plains,underground','Bestiary 5',false],
['Glaistig','','21','fey','forests,swamps','Bestiary 5',false],
['Goliath Frog','','3','animal','marshes,Rivers,Lakes,Oceans','Bestiary 5',false],
['Gravebound','','4','undead','lands,ruins','Bestiary 5',false],
['Gray','','4','humanoid','any','Bestiary 5',false],
['Gray Goo','','14','construct','any','Bestiary 5',false],
['Griefgall','','6','plant','forests,urban','Bestiary 5',false],
['Grim Reaper','','22','undead','any','Bestiary 5',false],
['Grimslake','','6','aberration','any','Bestiary 5',false],
['Grioth','','1','monstrous humanoid','any','Bestiary 5',false],
['Gristly Demodand','','17','outsider','any,Abyss','Bestiary 5',false],
['Guardian Scroll','','3','construct','any','Bestiary 5',false],
['Gunpowder Ooze','','14','ooze','any,lands','Bestiary 5',false],
['Hag eye Ooze','','3','ooze','marshes,underground','Bestiary 5',false],
['Heikegani','','4','aberration','coastlines','Bestiary 5',false],
['Heresy Devil','','12','outsider','Hell','Bestiary 5',false],
['Hobkins Gremlin','','0','fey','any','Bestiary 5',false],
['Horn Caterpillar','','1','vermin','forests','Bestiary 5',false],
['Hundun','','21','aberration','Abyss,Extraplanar,Extraplanar','Bestiary 5',false],
['Hunter Urchin','','6','vermin','oceans,coastlines','Bestiary 5',false],
['Ichthyocentaur','','5','monstrous humanoid','oceans,coastlines','Bestiary 5',false],
['Isonade','','15','magical beast','oceans','Bestiary 5',false],
['Jungle Drake','','6','dragon','jungles','Bestiary 5',false],
['Kabandha Cyclops','','9','humanoid','any,lands,underground','Bestiary 5',false],
['Kaprosuchus','','5','animal','forests','Bestiary 5',false],
['Karkadann','','4','magical beast','deserts','Bestiary 5',false],
['Kasa-obake Tsukumogami','','4','outsider','any','Bestiary 5',false],
['Kawa akago','','3','plant','marshes,rivers','Bestiary 5',false],
['Ketesthius','','13','magical beast','oceans,coastlines','Bestiary 5',false],
['Khala','','17','dragon','any,cold','Bestiary 5',false],
['Kikimora','','5','fey','urban','Bestiary 5',false],
['Kimenhul Sahkil','','20','outsider','any,Ethereal Plane','Bestiary 5',false],
['Koto-Furunishi Tsukumogami','','2','outsider','any','Bestiary 5',false],
['Boroboroton Tsukumogami','','5','outsider','any','Bestiary 5',false],
['Kurobozu','','6','undead','any','Bestiary 5',false],
['Lamhigyn','','3','outsider','any,Abyss','Bestiary 5',false],
['Lead Golem','','10','construct','any','Bestiary 5',false],
['Leechroot','','4','undead','forests','Bestiary 5',false],
['Leng Ghoul','','10','undead','any','Bestiary 5',false],
['Lesser Death','','16','undead','any','Bestiary 5',false],
['Liminal Sprite','','2','fey','urban','Bestiary 5',false],
['Living Mirage','','9','ooze','deserts,oceans','Bestiary 5',false],
['Locust Plague Swarm','','15','magical beast','any','Bestiary 5',false],
['Bat Plague Swarm','','17','magical beast','any','Bestiary 5',false],
['Lotus Leshy','','5','plant','lakes,rivers','Bestiary 5',false],
['Lotus Tree','','20','plant','coastlines,forests','Bestiary 5',false],
['Lusca','','17','magical beast','oceans','Bestiary 5',false],
['Maharishi Manu Manasaputra','','16','outsider','any,Extraplanar','Bestiary 5',false],
['Makara Vahana','','9','magical beast','any','Bestiary 5',false],
['Manu Manasaputra','','12','outsider','any,Extraplanar','Bestiary 5',false],
['Mngwa','','7','magical beast','forests','Bestiary 5',false],
['Moa','','2','animal','plains','Bestiary 5',false],
['Moon Dog','','9','outsider','any,Nirvana','Bestiary 5',false],
['Moon Giant','','15','humanoid','hills,mountains','Bestiary 5',false],
['Muckdweller','','-2','magical beast','marshes','Bestiary 5',false],
['Mummy Lord','cleric 9','10','undead','any','Bestiary 5',false],
['Muse','','16','fey','any','Bestiary 5',false],
['Mutant','barbarian 7','7','aberration','any','Bestiary 5',false],
['Myrmidon Robot','','11','construct','any','Bestiary 5',false],
['Narwhal','','3','animal','oceans','Bestiary 5',false],
['Blue Whale','','12','animal','oceans','Bestiary 5',false],
['Nemhain','','15','undead','any','Bestiary 5',false],
['Ningen','','16','monstrous humanoid','oceans','Bestiary 5',false],
['Nulmind','','11','plant','forests','Bestiary 5',false],
['Nuno Gremlin','','-2','fey','any,lands,underground','Bestiary 5',false],
['Ophiotaurus','','17','magical beast','hills,plains,swamps','Bestiary 5',false],
['Orang-pendak','fighter 1','0','humanoid','forests','Bestiary 5',false],
['Ostovite','','1','magical beast','any,Abyss','Bestiary 5',false],
['Ovinnik House Spirit','','2','fey','any,lands','Bestiary 5',false],
['Pakalchi Sahkil','','9','outsider','any,Ethereal Plane','Bestiary 5',false],
['Papinijuwari','','13','humanoid','plains','Bestiary 5',false],
['Penguin','','-1','animal','oceans','Bestiary 5',false],
['Peuchen','','10','magical beast','any,lands','Bestiary 5',false],
['Pharaonic Guardian','','11','undead','ruins','Bestiary 5',false],
['Plagued Beast','','2','undead','any','Bestiary 5',false],
['Plankta','','17','aberration','oceans','Bestiary 5',false],
['Plesiosaurus','','2','animal','swamps,Rivers,Lakes,Oceans','Bestiary 5',false],
['Polong','','8','undead','any','Bestiary 5',false],
['Psychemental','','8','outsider','any,Extraplanar','Bestiary 5',false],
['Psychepore','','7','plant','forests,jungles','Bestiary 5',false],
['Putrid Ooze','','11','ooze','any','Bestiary 5',false],
['Pyrausta','','-2','dragon','any','Bestiary 5',false],
['Qolok Sahkil','','16','outsider','any,Ethereal Plane','Bestiary 5',false],
['Ramidreju','','0','magical beast','any,lands','Bestiary 5',false],
['Rat Plague Swarm','','11','magical beast','any','Bestiary 5',false],
['Red Panda','','0','animal','forests,mountains','Bestiary 5',false],
['Reptoid','mesmerist 1','0','humanoid','any,lands','Bestiary 5',false],
['Rhu-chalik','','6','aberration','any','Bestiary 5',false],
['Riftcreeper','','15','ooze','mountains,Abyss','Bestiary 5',false],
['Annihilator Robot','','16','construct','any','Bestiary 5',false],
['Rishi Manu Manasaputra','','14','outsider','any,Extraplanar','Bestiary 5',false],
['Roiling Oil','','6','ooze','underground','Bestiary 5',false],
['Rope Dragon','','5','dragon','urban','Bestiary 5',false],
['Sangoi','','7','fey','any,lands','Bestiary 5',false],
['Saxra','','18','undead','mountains','Bestiary 5',false],
['Scarab Swarm','','3','vermin','deserts','Bestiary 5',false],
['Scitalis','','12','dragon','any,lands','Bestiary 5',false],
['Seal','','-1','animal','oceans','Bestiary 5',false],
['Seilenos','','19','fey','forests','Bestiary 5',false],
['Seraptis Demon','','15','outsider','any,Abyss','Bestiary 5',false],
['Sha','','4','magical beast','deserts','Bestiary 5',false],
['Shabti','oracle 1','0','outsider','any','Bestiary 5',false],
['Shadow Collector','','8','fey','any,lands','Bestiary 5',false],
['Shasalqu','','3','magical beast','deserts','Bestiary 5',false],
['Shen','','24','dragon','Rivers,Lakes,Oceans','Bestiary 5',false],
['Skinwalker','ranger 1','0','humanoid','forests,hills,mountains','Bestiary 5',false],
['Solar Pitri Manasaputra','','22','outsider','any,Extraplanar','Bestiary 5',false],
['Somalcygot','','12','aberration','any,vacuum','Bestiary 5',false],
['Spear Urchin','','4','vermin','oceans,coastlines','Bestiary 5',false],
['Sphinx Colossus','','14','construct','deserts','Bestiary 5',false],
['Storm Hag','','7','monstrous humanoid','any','Bestiary 5',false],
['Stormghost','','15','monstrous humanoid','mountains','Bestiary 5',false],
['Stranglereed','','9','plant','rivers,lakes','Bestiary 5',false],
['Stringy Demodand','','15','outsider','any,Abyss','Bestiary 5',false],
['Su','','8','magical beast','forests','Bestiary 5',false],
['Sun Giant','','16','humanoid','deserts,mountains','Bestiary 5',false],
['Swamp Mummy','','4','undead','swamps','Bestiary 5',false],
['Syricta','','12','aberration','any,lands','Bestiary 5',false],
['Taxidermic Creature','','3','construct','any','Bestiary 5',false],
['Termite Swarm','','6','vermin','forests,plains,underground','Bestiary 5',false],
['Terraformer Robot','','7','construct','any','Bestiary 5',false],
['Therizinosaurus','','10','animal','plains','Bestiary 5',false],
['Thought Eater','','2','aberration','any,Ethereal Plane','Bestiary 5',false],
['Thriae Constructor','','14','monstrous humanoid','any','Bestiary 5',false],
['Thriae Dancer','','6','monstrous humanoid','any','Bestiary 5',false],
['Tiyanak','','6','undead','forests','Bestiary 5',false],
['Tizheruk','','5','magical beast','rivers,marshes','Bestiary 5',false],
['Trench Mist','','10','aberration','any','Bestiary 5',false],
['Trilobite','','-2','vermin','oceans','Bestiary 5',false],
['Troodon','','1','animal','plains','Bestiary 5',false],
['Tsaalgrend','','2','plant','underground','Bestiary 5',false],
['Tulpa','monk 5','6','outsider','any','Bestiary 5',false],
['Turul','','19','outsider','any,Extraplanar','Bestiary 5',false],
['Twilight Pitri Manasaputra','','18','outsider','any,Extraplanar','Bestiary 5',false],
['Uintatherium','','7','animal','swamps','Bestiary 5',false],
['Undigested','','-2','undead','any','Bestiary 5',false],
['Undigested Swarm','','5','undead','any','Bestiary 5',false],
['Unfettered Phantom','','4','outsider','any,Ethereal Plane','Bestiary 5',false],
['Uraeus','','5','magical beast','rivers','Bestiary 5',false],
['Urannag','','8','construct','swamps,Abyss','Bestiary 5',false],
['Ursikka','','10','magical beast','any,lands','Bestiary 5',false],
['Ved','','5','humanoid','hills,mountains','Bestiary 5',false],
['Vescavor Queen','','9','outsider','any,Abyss','Bestiary 5',false],
['Vescavor Swarm','','5','outsider','any,Abyss','Bestiary 5',false],
['Vilderavn','','16','fey','any','Bestiary 5',false],
['Vishap','','19','dragon','any','Bestiary 5',false],
['Vukodlak','','3','undead','any,lands','Bestiary 5',false],
['Wakandagi','','14','outsider','rivers','Bestiary 5',false],
['Warmonger Devil','','7','outsider','any,Hell','Bestiary 5',false],
['Warmonger Wasp','','7','construct','any,Abyss','Bestiary 5',false],
['Water Leaper','','2','magical beast','lakes,swamps','Bestiary 5',false],
['Water Veela','','7','outsider','Rivers,Lakes,Oceans,Plane of Water','Bestiary 5',false],
['Water Wysp','','2','outsider','Plane of Water,Ethereal Plane','Bestiary 5',false],
['Wihsaak Sahkil','','6','outsider','any,Ethereal Plane','Bestiary 5',false],
['Witchcrow','','3','magical beast','forests,plains','Bestiary 5',false],
['Wizard\'s Shackle','','0','aberration','Rivers,Lakes,Oceans','Bestiary 5',false],
['Wolliped','','3','animal','hills','Bestiary 5',false],
['Wood Colossus','','17','construct','any,lands','Bestiary 5',false],
['Wyrmwraith','','17','undead','any','Bestiary 5',false],
['Xiao','','2','magical beast','mountains,forests','Bestiary 5',false],
['Yangethe','','9','aberration','forests,vacuum','Bestiary 5',false],
['Zygomind','','18','plant','any','Bestiary 5',false]
];
