//Name|Class|CR|Type|Terrain|Book/Page|isUnique
// 0 	== 1/2 CR
// -1 	== 1/3 CR
// -2	== 1/4 CR
// -3	== 1/6 CR
// -4	== 1/8 CR

var bestiary6 = [
['Algea','','11','outsider','Extraplanar','Bestiary 6',false],
['Cultist Troop','','11','humanoid','Underground','Bestiary 6',false],
['Erodaemon','','11','outsider','Abaddon','Bestiary 6',false],
['Gongorinan','','11','outsider','Abyss,Underground','Bestiary 6',false],
['Llorona','','11','undead','Coastlines,Swamps','Bestiary 6',false],
['Mapinguari','','11','magical beast','Forests','Bestiary 6',false],
['Razormouth Solifugid','','11','vermin','Mountains','Bestiary 6',false],
['Wild Hunt Horse','','11','fey','Lands','Bestiary 6',false],
['Alp','','10','fey','Lands','Bestiary 6',false],
['Blood Bramble','','10','plant','Forests','Bestiary 6',false],
['Bloody Bones','','10','undead','Lands','Bestiary 6',false],
['Daitengu','','10','outsider','Mountains','Bestiary 6',false],
['Fen Mauler','','10','monstrous humanoid','Swamps','Bestiary 6',false],
['Leng Hound','','10','aberration','Any','Bestiary 6',false],
['Muhuru','','10','magical beast','Forests','Bestiary 6',false],
['Vrykolakas','','10','undead','Any','Bestiary 6',false],
['Wild Hunt Hound','','10','fey','Lands','Bestiary 6',false],
['Zohanil','','10','outsider','Ethereal Plane','Bestiary 6',false],
['Amargasaurus','','6','animal','Forests,Plains','Bestiary 6',false],
['Annis Hag Alter Ego','','6','construct','cold,Swamps','Bestiary 6',false],
['Apocalypse Horse','','25','outsider','Abaddon','Bestiary 6',false],
['Isph-Aun-Vuln','','25','outsider','Abyss','Bestiary 6',true],
['Yarthoon','','25','magical beast','Cold,Vacuum','Bestiary 6',true],
['Apollyon','','29','outsider','Abaddon','Bestiary 6',true],
['Arshea','','29','outsider','Nirvana','Bestiary 6',true],
['Geryon','','29','outsider','Hell','Bestiary 6',true],
['Moloch','','29','outsider','Hell','Bestiary 6',true],
['Vorgozen','','29','ooze','Swamps','Bestiary 6',true],
['Baalzebul','','30','outsider','Hell','Bestiary 6',true],
['Charon','','30','outsider','Abaddon','Bestiary 6',true],
['Mephistopheles','','30','outsider','Hell','Bestiary 6',true],
['Tawil At\'Umr','','30','outsider','Any','Bestiary 6',true],
['Varklops','','30','magical beast','Mountains','Bestiary 6',false],
['Azuretzi','','5','outsider','Extraplanar','Bestiary 6',false],
['Banelight','','12','fey','Any','Bestiary 6',false],
['Bonethorn','','12','plant','Any','Bestiary 6',false],
['Ghole','','12','monstrous humanoid','Lands','Bestiary 6',false],
['Giant Sundew','','12','plant','Swamps','Bestiary 6',false],
['Gravesludge','','12','ooze','Lands','Bestiary 6',false],
['Obsidian Golem','','12','construct','Any','Bestiary 6',false],
['Tomb Giant','','12','humanoid','Lands,Underground','Bestiary 6',false],
['Vespergaunt','','12','ooze','Vacuum','Bestiary 6',false],
['Young Crypt dragon','','12','dragon','Extraplanar','Bestiary 6',false],
['Young Havoc dragon','','12','dragon','Elysium','Bestiary 6',false],
['Young Infernal dragon','','12','dragon','Hell','Bestiary 6',false],
['Young Paradise dragon','','12','dragon','Heaven','Bestiary 6',false],
['Young Rift dragon','','12','dragon','Abyss','Bestiary 6',false],
['Yurei','','12','undead','Lands','Bestiary 6',false],
['Behimiron','','13','outsider','Abyss','Bestiary 6',false],
['Clockwork Assassin','','13','construct','Any','Bestiary 6',false],
['Desert Blight','','13','ooze','deserts','Bestiary 6',false],
['Giganotosaurus','','13','animal','Forests,Plains','Bestiary 6',false],
['Kamaitachi','','13','fey','Any','Bestiary 6',false],
['Kikituk','','13','construct','Any','Bestiary 6',false],
['Oolioddroo','','13','outsider','Abyss','Bestiary 6',false],
['Oshageros','','13','outsider','Extraplanar','Bestiary 6',false],
['Psoglav','','13','monstrous humanoid','Underground','Bestiary 6',false],
['Shadow Giant','','13','humanoid','Plane of Shadow','Bestiary 6',false],
['Skrimsl','','13','magical beast','cold,Oceans','Bestiary 6',false],
['Slithering Pit','','2','ooze','Lands','Bestiary 6',false],
['Titanoboa','','13','animal','Swamps','Bestiary 6',false],
['Wild Hunt Archer','','13','fey','Lands','Bestiary 6',false],
['Atuikakura','','14','magical beast','Oceans','Bestiary 6',false],
['Deep Walker','','14','aberration','Oceans','Bestiary 6',false],
['Goezspall','','14','magical beast','Any','Bestiary 6',false],
['Mezlan','','14','ooze','Any','Bestiary 6',false],
['Mire Nettle','','2','plant','Swamps','Bestiary 6',false],
['Mountain Blight','','14','ooze','Mountains','Bestiary 6',false],
['Plague Giant','','14','humanoid','Lands','Bestiary 6',false],
['Rawhead','','14','monstrous humanoid','Lands','Bestiary 6',false],
['Temerdaemon','','14','outsider','Abaddon','Bestiary 6',false],
['Veiled Master','','14','aberration','Rivers,Lakes,Oceans','Bestiary 6',false],
['Clockwork Angel','','15','construct','Any','Bestiary 6',false],
['Gold Golem','','15','construct','Any','Bestiary 6',false],
['Hegessik','','15','outsider','Extraplanar','Bestiary 6',false],
['Memitim','','15','outsider','Extraplanar','Bestiary 6',false],
['Sewer Blight','','15','ooze','Underground,urban,ruins','Bestiary 6',false],
['Siabrae','Druid 14','15','undead','Lands','Bestiary 6',false],
['Targotha','','15','aberration','Swamps','Bestiary 6',false],
['Uinuja Azata','','15','outsider','Elysium','Bestiary 6',false],
['Wild Hunt Scout','','15','fey','Lands','Bestiary 6',false],
['Adult Crypt dragon','','16','dragon','Extraplanar','Bestiary 6',false],
['Adult Havoc dragon','','16','dragon','Elysium','Bestiary 6',false],
['Adult Infernal dragon','','16','dragon','Hell','Bestiary 6',false],
['Adult Paradise dragon','','16','dragon','Heaven','Bestiary 6',false],
['Adult Rift dragon','','16','dragon','Abyss','Bestiary 6',false],
['Cataboligne','','16','outsider','Abyss','Bestiary 6',false],
['Fire Whale','','16','magical beast','Plane of Fire','Bestiary 6',false],
['Saurian','','16','monstrous humanoid','Mountains','Bestiary 6',false],
['Titanic Whip Spider','','16','vermin','Hills','Bestiary 6',false],
['Tundra Blight','','16','ooze','cold,Plains','Bestiary 6',false],
['Barbatos','','26','outsider','Hell','Bestiary 6',true],
['Green Man','','26','plant','Forests','Bestiary 6',false],
['Ragathiel','','26','outsider','Heaven','Bestiary 6',true],
['Dispater','','27','outsider','Hell','Bestiary 6',true],
['Trelmarixian','','27','outsider','Abaddon','Bestiary 6',true],
['Yig','','27','monstrous humanoid','Any','Bestiary 6',true],
['Belial','','28','outsider','Hell','Bestiary 6',true],
['Black Butterfly','','28','outsider','Elysium','Bestiary 6',true],
['Mammon','','28','outsider','Hell','Bestiary 6',true],
['Rhan-Tegoth','','28','aberration','Any','Bestiary 6',true],
['Szuriel','','28','outsider','Abaddon','Bestiary 6',true],
['Blighted fey Satyr','','6','fey','Forests','Bestiary 6',false],
['Boggart','','4','fey','Forests,Swamps','Bestiary 6',false],
['Boggle','','8','fey','Lands','Bestiary 6',false],
['Brontotherium','','8','animal','Plains','Bestiary 6',false],
['Clockwork Guardian','','8','construct','Any','Bestiary 6',false],
['Fallen','','8','undead','Any','Bestiary 6',false],
['Giant Starfish','','8','vermin','Coastlines,Oceans','Bestiary 6',false],
['Hivemind Rat Swarm','','8','magical beast','Any','Bestiary 6',false],
['Horla','','8','aberration','Ethereal Plane','Bestiary 6',false],
['Pelagastr','','8','outsider','Extraplanar','Bestiary 6',false],
['Titan Centipede Exoskeleton','','8','undead','Forests,Underground','Bestiary 6',false],
['Utukku','','8','outsider','Abyss','Bestiary 6',false],
['Yaddithian','Wizard 9','8','aberration','Any','Bestiary 6',false],
['Brimorak','','5','outsider','Abyss','Bestiary 6',false],
['Calpina','','3','fey','Forests,Mountains','Bestiary 6',false],
['Cave Blight','','19','ooze','Underground','Bestiary 6',false],
['Obcisidaemon','','19','outsider','Abaddon','Bestiary 6',false],
['Tarantula Tree','','19','plant','Forests','Bestiary 6',false],
['Warmonger','','19','construct','Any','Bestiary 6',false],
['Wild Hunt Monarch','','19','fey','Lands','Bestiary 6',false],
['Euryale','','20','monstrous humanoid','Any','Bestiary 6',false],
['Izfiitar','','20','outsider','Extraplanar','Bestiary 6',false],
['Oblivion','','20','ooze','Extraplanar','Bestiary 6',false],
['Quintessence Golem','','20','construct','Any','Bestiary 6',false],
['Veranallia Azata','','20','outsider','Elysium','Bestiary 6',false],
['Whisperer','','20','fey','Forests,Plains,Mountains,Hills','Bestiary 6',false],
['Ancient Crypt dragon','','21','dragon','Extraplanar','Bestiary 6',false],
['Ancient Havoc dragon','','21','dragon','Elysium','Bestiary 6',false],
['Ancient Infernal dragon','','21','dragon','Hell','Bestiary 6',false],
['Ancient Paradise dragon','','21','dragon','Heaven','Bestiary 6',false],
['Ancient Rift dragon','','21','dragon','Abyss','Bestiary 6',false],
['Cipactli','','21','magical beast','Rivers,Lakes,Oceans','Bestiary 6',false],
['Conqueror Worm','','21','aberration','Any','Bestiary 6',false],
['Krampus','','21','monstrous humanoid','Any','Bestiary 6',false],
['Ouroboros','','21','magical beast','Extraplanar','Bestiary 6',false],
['Thuskchoon','','21','outsider','Abyss','Bestiary 6',true],
['Chavazvug','','22','outsider','Abyss','Bestiary 6',true],
['Charnel God','','23','construct','Any','Bestiary 6',false],
['Oaur-Ooung','','23','outsider','Abyss','Bestiary 6',true],
['Clockwork Fiend','','17','construct','Any','Bestiary 6',false],
['Lilitu','','17','outsider','Abyss','Bestiary 6',false],
['Olethros','','17','outsider','Extraplanar','Bestiary 6',false],
['Phasmadaemon','','17','outsider','Abaddon','Bestiary 6',false],
['Swamp Blight','','17','ooze','Swamps','Bestiary 6',false],
['Whaler Jellyfish','','17','vermin','Oceans','Bestiary 6',false],
['Ximtal','','17','outsider','Ethereal Plane','Bestiary 6',false],
['Deathsnatcher','','18','monstrous humanoid','Deserts,Mountains','Bestiary 6',false],
['Duneshaker Solifugid','','18','vermin','Deserts','Bestiary 6',false],
['Forest Blight','','18','ooze','Forests','Bestiary 6',false],
['Mosslord','','18','plant','Forests','Bestiary 6',false],
['Mountain Giant','','18','humanoid','Mountains','Bestiary 6',false],
['Omnipath','','18','aberration','Rivers,Lakes,Oceans','Bestiary 6',false],
['Thessalhydra','','18','aberration','Swamps','Bestiary 6',false],
['Vavakia','','18','outsider','Abyss','Bestiary 6',false],
['Viridium Golem','','18','construct','Any','Bestiary 6',false],
['Clockwork Hound','','5','construct','Any','Bestiary 6',false],
['Coffin Anemone','','1','vermin','Coastlines,Oceans','Bestiary 6',false],
['Siren\'s Bed Anemone','','9','vermin','Coastlines,Oceans','Bestiary 6',false],
['Combusted','','3','undead','Any','Bestiary 6',false],
['Common Eurypterid','','1','vermin','Oceans','Bestiary 6',false],
['Coral Capuchin','','1','magical beast','Coastlines,Oceans','Bestiary 6',false],
['Crimson Jellyfish','','4','vermin','Oceans','Bestiary 6',false],
['Crypt Flower','','7','plant','Lands','Bestiary 6',false],
['Cryptguard','','9','construct','Any','Bestiary 6',false],
['Dream Naga','','9','aberration','Extraplanar','Bestiary 6',false],
['Elasmotherium','','9','animal','Forests,Plains','Bestiary 6',false],
['Fungus Queen','','9','plant','Underground','Bestiary 6',false],
['Cutlass Spider','','6','construct','Any','Bestiary 6',false],
['Danthienne','','5','fey','Urban','Bestiary 6',false],
['Deinotherium','','7','animal','Forests,Plains','Bestiary 6',false],
['Derro Magister','','5','humanoid','Underground','Bestiary 6',false],
['Devil Monkey','','6','animal','Hills,Plains','Bestiary 6',false],
['Dunkleosteus','','6','animal','Oceans','Bestiary 6',false],
['Elder Wyrm','','24','dragon','Any','Bestiary 6',false],
['Esobok','','3','outsider','Extraplanar','Bestiary 6',false],
['Exiled Shade','','6','undead','Any','Bestiary 6',false],
['Giant Ant Spore Zombie','','3','undead','Any','Bestiary 6',false],
['Giant Belostomatid','','3','vermin','Lakes,Rivers,Swamps','Bestiary 6',false],
['Giant Cockroach Exoskeleton','','0','undead','Forests,Underground','Bestiary 6',false],
['Giant Hellgrammite','','5','vermin','Lakes,Rivers,Swamps','Bestiary 6',false],
['Giant Raven','','1','animal','Any','Bestiary 6',false],
['Giant Stag Beetle Exoskeleton','','4','undead','Forests,Underground','Bestiary 6',false],
['Gluttongrass','','1','plant','Plains','Bestiary 6',false],
['Goblin Troop','','5','humanoid','Forests,Plains,Coastlines','Bestiary 6',false],
['Gorgoros','','9','outsider','Abyss','Bestiary 6',false],
['Herecite','','9','undead','Any','Bestiary 6',false],
['Medusa Animus Shade','','9','undead','Swamps,Underground','Bestiary 6',false],
['Mokele-Mbembe','','9','animal','Lakes,Rivers','Bestiary 6',false],
['Gowrow','','5','dragon','Lakes,Rivers','Bestiary 6',false],
['Hookfang Worm','','7','vermin','Oceans','Bestiary 6',false],
['Giant Tube Worm','','2','vermin','Oceans','Bestiary 6',false],
['Hupia','','6','undead','Lands','Bestiary 6',false],
['Hydraggon','','3','outsider','Rivers,Lakes,Oceans','Bestiary 6',false],
['Ichkoh','','7','outsider','Ethereal Plane','Bestiary 6',false],
['Kentrosaurus','','5','animal','Plains','Bestiary 6',false],
['Lacridaemon','','3','outsider','Abaddon','Bestiary 6',false],
['Lovelorn','','4','undead','Any','Bestiary 6',false],
['Mockingfey','','1','fey','Forests','Bestiary 6',false],
['Moldwretch','','7','plant','Swamps,Underground','Bestiary 6',false],
['Mongrel Cave Giant','','7','humanoid','Underground','Bestiary 6',false],
['Monkey Goblin','Barbarian 1','0','humanoid','Forests','Bestiary 6',false],
['Munavri','Mesmerist 1','1','humanoid','Underground','Bestiary 6',false],
['Naiad','Bard 1','0','fey','Rivers,Lakes,Oceans','Bestiary 6',false],
['Nekomata','','6','magical beast','Lands','Bestiary 6',false],
['Ourdivar','','4','outsider','Extraplanar','Bestiary 6',false],
['Outlaw Troop','','7','humanoid','Lands','Bestiary 6',false],
['Piranha Swarm','','3','animal','Rivers,Lakes,Oceans','Bestiary 6',false],
['Psychic Stalker','','7','undead','Any','Bestiary 6',false],
['Quetzalcoatlus','','7','animal','Coastlines,Plains,Swamps','Bestiary 6',false],
['Raven Swarm','','3','animal','Any','Bestiary 6',false],
['Rougarou','Ranger 1','0','humanoid','Lands','Bestiary 6',false],
['Sangudaemon','','9','outsider','Abaddon','Bestiary 6',false],
['Shoki','','9','outsider','Extraplanar','Bestiary 6',false],
['Slime Naga','','9','aberration','Underground','Bestiary 6',false],
['Spiny Eurypterid','','9','vermin','Oceans','Bestiary 6',false],
['Skincrawler','','0','ooze','Any','Bestiary 6',false],
['Suspiridaemon','','7','outsider','Abaddon','Bestiary 6',false],
['Taniwha','','6','magical beast','Rivers','Bestiary 6',false],
['Tenome','','4','monstrous humanoid','Urban','Bestiary 6',false],
['Trailgaunt','','3','undead','Lands','Bestiary 6',false],
['Unrisen','','5','undead','Any','Bestiary 6',false],
['Urhag','','3','aberration','cold,Mountains','Bestiary 6',false],
['Venedaemon','','5','outsider','Abaddon','Bestiary 6',false],
['Vermlek','','3','outsider','Abyss,Any','Bestiary 6',false],
['Viduus','','4','outsider','Extraplanar','Bestiary 6',false],
['Weremantis','Monk 3','4','humanoid','Lands','Bestiary 6',false],
['Werespider','Rogue','2','humanoid','Any','Bestiary 6',false],
['Werewasp','Cleric 5','5','humanoid','Lands','Bestiary 6',false],
['Yaenit','','6','outsider','Abyss','Bestiary 6',false],
['Yamah Azata','','5','outsider','Elysium','Bestiary 6',false]
]