//Name|Class|CR|Type|Terrain|Book/Page|isUnique
// 0 	== 1/2 CR
// -1 	== 1/3 CR
// -2	== 1/4 CR
// -3	== 1/6 CR
// -4	== 1/8 CR

var bestiary2 = [
['Achaierai','','5','outsider','lands,Hell','Bestiary 2',false],
['Akhana','','12','outsider','Extraplanar','Bestiary 2',false],
['Bythos','','16','outsider','Extraplanar','Bestiary 2',false],
['Paracletus','','2','outsider','Extraplanar','Bestiary 2',false],
['Pleroma','','20','outsider','Extraplanar','Bestiary 2',false],
['Theletos','','7','outsider','Extraplanar','Bestiary 2',false],
['Avoral','','9','outsider','Nirvana','Bestiary 2',false],
['Draconal','','20','outsider','Nirvana','Bestiary 2',false],
['Cetaceal','','15','outsider','Nirvana','Bestiary 2',false],
['Draconal','','20','outsider','Nirvana','Bestiary 2',false],
['Leonal','','12','outsider','Nirvana','Bestiary 2',false],
['Silvanshee','','2','outsider','Nirvana','Bestiary 2',false],
['Vulpinal','','6','outsider','Nirvana','Bestiary 2',false],
['Akata','','1','aberration','any','Bestiary 2',false],
['Amoeba Swarm','','1','ooze','lands,underground','Bestiary 2',false],
['Amoeba,Giant','','1','ooze','lands,underground','Bestiary 2',false],
['Amphisbaena','','4','magical beast','hills,underground','Bestiary 2',false],
['Cassisian','','2','outsider','Extraplanar','Bestiary 2',false],
['Monadic Deva','','12','outsider','Extraplanar','Bestiary 2',false],
['Movanic Deva','','10','outsider','Extraplanar','Bestiary 2',false],
['Animate Dream','','8','outsider','Ethereal Plane','Bestiary 2',false],
['Aranea','','4','magical beast','jungles,forests','Bestiary 2',false],
['Shield Archon','','10','outsider','Heaven','Bestiary 2',false],
['Star Archon','','19','outsider','Heaven','Bestiary 2',false],
['Athach','','12','humanoid','cold,hills','Bestiary 2',false],
['Attic Whisperer','','4','undead','urban,ruins','Bestiary 2',false],
['Aurumvorax','','9','magical beast','plains,hills,forests','Bestiary 2',false],
['Axiomite','','8','outsider','Any','Bestiary 2',false],
['Brijidine','','17','outsider','Elysium','Bestiary 2',false],
['Lyrakien','','2','outsider','Elysium','Bestiary 2',false],
['Azer','','2','outsider','lands,Plane of Fire','Bestiary 2',false],
['Badger','','0','animal','forests','Bestiary 2',false],
['Dire Badger','','2','animal','forests','Bestiary 2',false],
['Banshee','','13','undead','any','Bestiary 2',false],
['Mobat Bat','','3','magical beast','forests,hills','Bestiary 2',false],
['Skaveling Bat','','5','undead','underground','Bestiary 2',false],
['Giant Bee','','1','vermin','plains','Bestiary 2',false],
['Giant Queen Bee','','5','vermin','plains','Bestiary 2',false],
['Goliath Stag Beetle','','8','vermin','forests,plains','Bestiary 2',false],
['Slicer Beetle','','4','vermin','forests','Bestiary 2',false],
['Belker','','6','outsider','Plane of Air','Bestiary 2',false],
['Blindheim','','2','magical beast','underground','Bestiary 2',false],
['Blink Dog','','2','magical beast','plains,forests','Bestiary 2',false],
['Bodak','','8','undead','lands,Extraplanar','Bestiary 2',false],
['Brownie','','1','fey','forests,plains','Bestiary 2',false],
['Bunyip','','3','magical beast','lakes,rivers,oceans','Bestiary 2',false],
['Carnivorous Blob','','13','ooze','any','Bestiary 2',false],
['Catoblepas','','12','magical beast','swamps','Bestiary 2',false],
['Giant Whiptail Centipede','','3','vermin','forests,underground','Bestiary 2',false],
['Titan Centipede','','9','vermin','forests,underground','Bestiary 2',false],
['Chaos Beast','','7','outsider','any','Bestiary 2',false],
['Charda','','7','monstrous humanoid','rivers,lakes,cold,underground','Bestiary 2',false],
['Charybdis','','13','aberration','oceans','Bestiary 2',false],
['Chupacabra','','2','magical beast','forests,hills','Bestiary 2',false],
['Cockroach Swarm','','2','vermin','urban','Bestiary 2',false],
['Giant Cockroach','','0','vermin','lands','Bestiary 2',false],
['Crawling Hand','','0','undead','lands','Bestiary 2',false],
['Giant Crawling Hand','','5','undead','lands,underground','Bestiary 2',false],
['Crypt Thing','','5','undead','underground','Bestiary 2',false],
['Crysmal','','3','outsider','underground,Plane of Earth','Bestiary 2',false],
['D\'ziriak','','3','outsider','Plane of Shadow','Bestiary 2',false],
['Astradaemon','','16','outsider','Abaddon,Extraplanar','Bestiary 2',false],
['Cacodaemon','','2','outsider','Abaddon','Bestiary 2',false],
['Ceustodaemon','','6','outsider','Abaddon','Bestiary 2',false],
['Derghodaemon','','10','outsider','Abaddon','Bestiary 2',false],
['Hydrodaemon','','7','outsider','Abaddon','Bestiary 2',false],
['Leukodaemon','','9','outsider','Abaddon','Bestiary 2',false],
['Meladaemon','','11','outsider','Abaddon','Bestiary 2',false],
['Olethrodaemon','','20','outsider','Abaddon','Bestiary 2',false],
['Piscodaemon','','10','outsider','Abaddon','Bestiary 2',false],
['Purrodaemon','','18','outsider','Abaddon','Bestiary 2',false],
['Thanadaemon','','13','outsider','Abaddon','Bestiary 2',false],
['Dark Slayer','','3','humanoid','underground','Bestiary 2',false],
['Death Worm','','6','magical beast','deserts,plains,hills','Bestiary 2',false],
['Decapus','','3','aberration','forests,underground','Bestiary 2',false],
['Kalavakus','','10','outsider','Abyss','Bestiary 2',false],
['Omox','','12','outsider','Abyss','Bestiary 2',false],
['Shemhazian','','16','outsider','Abyss','Bestiary 2',false],
['Vrolikai','','19','outsider','Abyss','Bestiary 2',false],
['Denizen of Leng','','8','outsider','lands','Bestiary 2',false],
['Destrachan','','8','aberration','underground','Bestiary 2',false],
['Accuser Devil','','3','outsider','Hell','Bestiary 2',false],
['Belier Devil','','16','outsider','Hell','Bestiary 2',false],
['Handmaiden Devil','','14','outsider','Hell','Bestiary 2',false],
['Immolation Devil','','19','outsider','Hell','Bestiary 2',false],
['Devilfish','','4','magical beast','oceans,lakes,rivers,Abyss','Bestiary 2',false],
['Dhampir','fighter 1','0','humanoid','lands','Bestiary 2',false],
['Allosaurus','','7','animal','forests,plains','Bestiary 2',false],
['Compsognathus','','0','animal','forests,plains','Bestiary 2',false],
['Parasaurolophus','','4','animal','forests,plains','Bestiary 2',false],
['Tylosaurus','','8','animal','oceans,lakes,rivers','Bestiary 2',false],
['Dragon Horse','','7','magical beast','any','Bestiary 2',false],
['Adult Brine Dragon','','11','dragon','coastlines,oceans,rivers,Plane of Water','Bestiary 2',false],
['Ancient Brine Dragon','','16','dragon','coastlines,oceans,rivers,Plane of Water','Bestiary 2',false],
['Young Brine Dragon','','7','dragon','coastlines,oceans,rivers,Plane of Water','Bestiary 2',false],
['Adult Cloud Dragon','','11','dragon','air,Plane of Air','Bestiary 2',false],
['Ancient Cloud Dragon','','16','dragon','air,Plane of Air','Bestiary 2',false],
['Young Cloud Dragon','','7','dragon','air,Plane of Air','Bestiary 2',false],
['Adult Crystal Dragon','','10','dragon','underground,Plane of Earth','Bestiary 2',false],
['Ancient Crystal Dragon','','15','dragon','underground,Plane of Earth','Bestiary 2',false],
['Young Crystal Dragon','','6','dragon','underground,Plane of Earth','Bestiary 2',false],
['Adult Magma Dragon','','12','dragon','mountains,underground,Plane of Fire','Bestiary 2',false],
['Ancient Magma Dragon','','17','dragon','mountains,underground,Plane of Fire','Bestiary 2',false],
['Young Magma Dragon','','8','dragon','mountains,underground,Plane of Fire','Bestiary 2',false],
['Adult Umbral Dragon','','14','dragon','any','Bestiary 2',false],
['Ancient Umbral Dragon','','19','dragon','any','Bestiary 2',false],
['Young Umbral Dragon','','10','dragon','any','Bestiary 2',false],
['Giant Dragonfly','','4','vermin','lands','Bestiary 2',false],
['Giant Dragonfly Nymph','','3','vermin','lakes,rivers','Bestiary 2',false],
['Flame Drake','','5','dragon','mountains,hills','Bestiary 2',false],
['Forest Drake','','4','dragon','forests','Bestiary 2',false],
['Frost Drake','','7','dragon','mountains','Bestiary 2',false],
['Sea Drake','','6','dragon','coastlines','Bestiary 2',false],
['Draugr','','2','undead','coastlines','Bestiary 2',false],
['Dullahan','','7','undead','any','Bestiary 2',false],
['Dust Digger','','4','aberration','deserts','Bestiary 2',false],
['Elder Ice Elemental','','11','outsider','lands,cold,lakes,rivers,Plane of Water','Bestiary 2',false],
['Greater Ice Elemental','','9','outsider','lands,cold,lakes,rivers,Plane of Water','Bestiary 2',false],
['Huge Ice Elemental','','7','outsider','lands,cold,lakes,rivers,Plane of Water','Bestiary 2',false],
['Large Ice Elemental','','5','outsider','lands,cold,lakes,rivers,Plane of Water','Bestiary 2',false],
['Medium Ice Elemental','','3','outsider','lands,cold,lakes,rivers,Plane of Water','Bestiary 2',false],
['Small Ice Elemental','','1','outsider','lands,cold,lakes,rivers,Plane of Water','Bestiary 2',false],
['Elder Lightning Elemental','','11','outsider','Plane of Air','Bestiary 2',false],
['Greater Lightning Elemental','','9','outsider','Plane of Air','Bestiary 2',false],
['Huge Lightning Elemental','','7','outsider','Plane of Air','Bestiary 2',false],
['Large Lightning Elemental','','5','outsider','Plane of Air','Bestiary 2',false],
['Medium Lightning Elemental','','3','outsider','Plane of Air','Bestiary 2',false],
['Small Lightning Elemental','','1','outsider','Plane of Air','Bestiary 2',false],
['Elder Magma Elemental','','11','outsider','Plane of Fire','Bestiary 2',false],
['Greater Magma Elemental','','9','outsider','Plane of Fire','Bestiary 2',false],
['Huge Magma Elemental','','7','outsider','Plane of Fire','Bestiary 2',false],
['Large Magma Elemental','','5','outsider','Plane of Fire','Bestiary 2',false],
['Medium Magma Elemental','','3','outsider','Plane of Fire','Bestiary 2',false],
['Small Magma Elemental','','1','outsider','Plane of Fire','Bestiary 2',false],
['Elder Mud Elemental','','11','outsider','lands,rivers,swamps,lakes,Plane of Earth','Bestiary 2',false],
['Greater Mud Elemental','','9','outsider','lands,rivers,swamps,lakes,Plane of Earth','Bestiary 2',false],
['Huge Mud Elemental','','7','outsider','lands,rivers,swamps,lakes,Plane of Earth','Bestiary 2',false],
['Large Mud Elemental','','5','outsider','lands,rivers,swamps,lakes,Plane of Earth','Bestiary 2',false],
['Medium Mud Elemental','','3','outsider','lands,rivers,swamps,lakes,Plane of Earth','Bestiary 2',false],
['Small Mud Elemental','','1','outsider','lands,rivers,swamps,lakes,Plane of Earth','Bestiary 2',false],
['Faceless Stalker','','4','aberration','swamps,underground','Bestiary 2',false],
['Fetchling','rogue 1','0','outsider','Plane of Shadow','Bestiary 2',false],
['Giant Fly','','1','vermin','any,jungles','Bestiary 2',false],
['Giant Maggot','','0','vermin','any,jungles','Bestiary 2',false],
['Forlarren','','2','fey','plains,forests','Bestiary 2',false],
['Frost Worm','','12','magical beast','cold,plains,mountains','Bestiary 2',false],
['Fungal Crawler','','3','aberration','underground','Bestiary 2',false],
['Gar','','1','animal','lakes,rivers','Bestiary 2',false],
['Giant Gar','','6','animal','lakes,rivers','Bestiary 2',false],
['Marsh Giant','','8','humanoid','marshes','Bestiary 2',false],
['Rune Giant','','17','humanoid','cold,mountains','Bestiary 2',false],
['Taiga Giant','','12','humanoid','cold,mountains,forests','Bestiary 2',false],
['Wood Giant','','5','humanoid','forests','Bestiary 2',false],
['Gloomwing','','4','outsider','Plane of Shadow','Bestiary 2',false],
['Adamantine Golem','','19','construct','any','Bestiary 2',false],
['Alchemical Golem','','9','construct','any','Bestiary 2',false],
['Carrion Golem','','4','construct','lands','Bestiary 2',false],
['Clockwork Golem','','12','construct','any','Bestiary 2',false],
['Glass Golem','','8','construct','lands','Bestiary 2',false],
['Mithral Golem','','16','construct','any','Bestiary 2',false],
['Gray Render','','8','magical beast','marshes','Bestiary 2',false],
['Jinkin','','1','fey','underground,urban','Bestiary 2',false],
['Nuglub','','2','fey','underground,urban','Bestiary 2',false],
['Pugwampi','','0','fey','hills','Bestiary 2',false],
['Vexgit','','1','fey','underground,urban','Bestiary 2',false],
['Grick','','3','aberration','underground','Bestiary 2',false],
['Grig','','1','fey','forests','Bestiary 2',false],
['Grindylow','','0','aberration','coastlines,oceans','Bestiary 2',false],
['Grippli','warrior 1','-1','humanoid','forests,marshes','Bestiary 2',false],
['Gryph','','1','magical beast','underground','Bestiary 2',false],
['Gug','','10','aberration','underground','Bestiary 2',false],
['Hangman Tree','','7','plant','forests','Bestiary 2',false],
['Hellcat','','7','outsider','lands,Hell','Bestiary 2',false],
['Camel','','1','animal','deserts','Bestiary 2',false],
['Ram','','1','animal','mountains','Bestiary 2',false],
['Hippocampus','','1','magical beast','oceans,lakes,rivers,coastlines','Bestiary 2',false],
['Hippogriff','','2','magical beast','hills,plains','Bestiary 2',false],
['Hippopotamus','','4','animal','water,plains','Bestiary 2',false],
['Behemoth Hippopotamus','','10','animal','rivers','Bestiary 2',false],
['Hound of Tindalos','','7','outsider','any','Bestiary 2',false],
['Howler','','3','outsider','lands,Abyss','Bestiary 2',false],
['Ifrit','sorcerer 1','0','outsider','lands','Bestiary 2',false],
['Arbiter','','2','outsider','any','Bestiary 2',false],
['Kolyarut','','12','outsider','any','Bestiary 2',false],
['Lhaksharut','','20','outsider','any','Bestiary 2',false],
['Marut','','15','outsider','any','Bestiary 2',false],
['Zelekhut','','9','outsider','lands','Bestiary 2',false],
['Giant Jellyfish','','7','vermin','oceans','Bestiary 2',false],
['Sapphire Jellyfish','','11','vermin','oceans,lakes,rivers,coastlines','Bestiary 2',false],
['Jyoti','','9','outsider','Extraplanar','Bestiary 2',false],
['Kelpie','','4','fey','rivers,lakes,swamps','Bestiary 2',false],
['Korred','','4','fey','forests','Bestiary 2',false],
['Krenshar','','1','magical beast','forests,plains','Bestiary 2',false],
['Lamia Matriarch','','8','monstrous humanoid','lands','Bestiary 2',false],
['Leng Spider','','14','magical beast','any','Bestiary 2',false],
['Leprechaun','','2','fey','forests','Bestiary 2',false],
['Leucrotta','','5','magical beast','jungles,forests,hills','Bestiary 2',false],
['Locathah','','0','humanoid','water','Bestiary 2',false],
['Lurker In Light','','5','fey','lands,extraplanar','Bestiary 2',false],
['Werebear','ranger 4','4','humanoid','forests','Bestiary 2',false],
['Wereboar','barbarian 2','2','humanoid','forests,plains','Bestiary 2',false],
['Weretiger','rogue 4','4','humanoid','plains,swamps','Bestiary 2',false],
['Giant Maggot','','0','vermin','jungles','Bestiary 2',false],
['Mandragora','','1','plant','cold,forests','Bestiary 2',false],
['Arsinoitherium','','7','animal','plains','Bestiary 2',false],
['Megaloceros','','4','animal','cold,forests,plains','Bestiary 2',false],
['Megatherium','','5','animal','forests','Bestiary 2',false],
['Mercane','','5','outsider','lands,underground','Bestiary 2',false],
['Merrow,Freshwater','','3','humanoid','lakes,rivers','Bestiary 2',false],
['Merrow,Saltwater','','6','humanoid','oceans','Bestiary 2',false],
['Mihstu','','6','outsider','Plane of Air','Bestiary 2',false],
['Mongrelman','','1','monstrous humanoid','ruins,underground','Bestiary 2',false],
['Moonflower','','8','plant','lands','Bestiary 2',false],
['Mosquito Swarm','','3','vermin','jungles,swamps','Bestiary 2',false],
['Giant Mosquito','','0','vermin','marshes','Bestiary 2',false],
['Mothman','','6','monstrous humanoid','lands','Bestiary 2',false],
['Mu Spore','','21','plant','any','Bestiary 2',false],
['Necrophidius','','2','construct','any','Bestiary 2',false],
['Neh-thalggu','','8','aberration','any','Bestiary 2',false],
['Nereid','','10','fey','water','Bestiary 2',false],
['Nightcrawler','','18','undead','Extraplanar','Bestiary 2',false],
['Nightwalker','','16','undead','Extraplanar','Bestiary 2',false],
['Nightwave','','20','undead','Extraplanar','Bestiary 2',false],
['Nightwing','','14','undead','Extraplanar','Bestiary 2',false],
['Ogrekin','fighter 2','2','humanoid','any','Bestiary 2',false],
['Magma Ooze','','7','ooze','mountains,underground','Bestiary 2',false],
['Pech','','3','fey','underground,Plane of Earth','Bestiary 2',false],
['Peryton','','4','magical beast','any','Bestiary 2',false],
['Petitioner','','1','outsider','Extraplanar','Bestiary 2',false],
['Phycomid','','4','plant','underground','Bestiary 2',false],
['Poltergeist','','2','undead','any','Bestiary 2',false],
['Baboon','','0','animal','forests,plains','Bestiary 2',false],
['Monkey Swarm','','2','animal','forests','Bestiary 2',false],
['Imentesh','','10','outsider','Extraplanar','Bestiary 2',false],
['Keketar','','17','outsider','Extraplanar','Bestiary 2',false],
['Naunet','','7','outsider','Extraplanar','Bestiary 2',false],
['Voidworm','','2','outsider','Extraplanar','Bestiary 2',false],
['Augnagar','','14','outsider','Abyss','Bestiary 2',false],
['Chernobue','','12','outsider','Abyss','Bestiary 2',false],
['Cythnigot','','2','outsider','Abyss','Bestiary 2',false],
['Iathavos','','20','outsider','Abyss','Bestiary 2',false],
['Nyogoth','','10','outsider','Abyss','Bestiary 2',false],
['Shoggti','','7','outsider','Abyss','Bestiary 2',false],
['Thulgant','','18','outsider','Abyss','Bestiary 2',false],
['Quickling','','3','fey','forests','Bestiary 2',false],
['Quickwood','','8','plant','forests','Bestiary 2',false],
['Rast','','5','outsider','Plane of Fire','Bestiary 2',false],
['Red Wyrm Ravener','','22','undead','mountains','Bestiary 2',false],
['Manta Ray','','1','animal','oceans','Bestiary 2',false],
['Redcap','','2','fey','forests,underground','Bestiary 2',false],
['Reefclaw','','1','aberration','coastlines,rivers,lakes,oceans','Bestiary 2',false],
['Revenant','','6','undead','lands','Bestiary 2',false],
['Sandman','','3','outsider','Plane of Earth','Bestiary 2',false],
['Scarecrow','','4','construct','lands','Bestiary 2',false],
['Sceaduinar','','7','outsider','Extraplanar','Bestiary 2',false],
['Black Scorpion','','15','vermin','deserts','Bestiary 2',false],
['Cave Scorpion','','1','vermin','underground','Bestiary 2',false],
['Scylla','','10','magical beast','water','Bestiary 2',false],
['Serpentfolk','','4','monstrous humanoid','lands','Bestiary 2',false],
['Seugathi','','6','aberration','underground','Bestiary 2',false],
['Shantak','','8','magical beast','cold,mountains','Bestiary 2',false],
['Shining Child','','12','outsider','lands,extraplanar','Bestiary 2',false],
['Sinspawn','','2','aberration','ruins','Bestiary 2',false],
['Siren','','5','magical beast','hills','Bestiary 2',false],
['Skulk','','1','humanoid','lands,underground','Bestiary 2',false],
['Slime Mold','','2','ooze','forests','Bestiary 2',false],
['Slithering Tracker','','3','ooze','underground','Bestiary 2',false],
['Slurk','','2','magical beast','swamps,underground','Bestiary 2',false],
['Emperor Cobra','','5','animal','swamps','Bestiary 2',false],
['Giant Anaconda','','10','animal','swamps','Bestiary 2',false],
['Albino Cave Solifugid','','4','vermin','underground','Bestiary 2',false],
['Giant Solifugid','','1','vermin','deserts','Bestiary 2',false],
['Soul Eater','','7','outsider','Abaddon,Extraplanar','Bestiary 2',false],
['Soulbound Doll','','2','construct','any','Bestiary 2',false],
['Giant Black Widow Spider','','3','vermin','lands','Bestiary 2',false],
['Giant Tarantula','','8','vermin','forests','Bestiary 2',false],
['Spriggan','','3','humanoid','hills,forests','Bestiary 2',false],
['Sylph','rogue 1','0','outsider','lands','Bestiary 2',false],
['Jabberwock','','23','dragon','forests','Bestiary 2',false],
['Sard','','19','plant','forests','Bestiary 2',false],
['Thrasfyr','','17','magical beast','any','Bestiary 2',false],
['Tendriculos','','6','plant','forests','Bestiary 2',false],
['Tenebrous Worm','','8','outsider','lands','Bestiary 2',false],
['Tentamort','','4','aberration','underground','Bestiary 2',false],
['Thoqqua','','2','outsider','lands','Bestiary 2',false],
['Thunderbird','','11','magical beast','hills','Bestiary 2',false],
['Tick Swarm','','9','vermin','forests','Bestiary 2',false],
['Giant Tick','','1','vermin','forests','Bestiary 2',false],
['Elysian Titan','','21','outsider','lands,Elysium','Bestiary 2',false],
['Thanatotic Titan','','22','outsider','Abyss','Bestiary 2',false],
['Giant Toad','','2','animal','forests','Bestiary 2',false],
['Glacier Toad','','6','magical beast','cold,hills','Bestiary 2',false],
['Totenmaske','','7','undead','lands','Bestiary 2',false],
['Triton','','2','outsider','oceans','Bestiary 2',false],
['Ice Troll','','3','humanoid','cold,mountains','Bestiary 2',false],
['Rock Troll','','6','humanoid','underground','Bestiary 2',false],
['Giant Snapping Turtle','','9','animal','coastlines','Bestiary 2',false],
['Snapping Turtle','','-1','animal','coastlines','Bestiary 2',false],
['Twigjack','','3','fey','forests','Bestiary 2',false],
['Undine','cleric 1','0','outsider','lands','Bestiary 2',false],
['Urdefhan','','3','outsider','lands,Abaddon','Bestiary 2',false],
['Vampiric Mist','','3','aberration','swamps,underground','Bestiary 2',false],
['Vemerak','','14','aberration','underground','Bestiary 2',false],
['Viper Vine','','13','plant','forests,swamps','Bestiary 2',false],
['Water Orm','','10','magical beast','lakes','Bestiary 2',false],
['Wendigo','','17','outsider','cold,any','Bestiary 2',false],
['Whale','','10','animal','oceans','Bestiary 2',false],
['Great White Whale','','14','animal','oceans','Bestiary 2',false],
['Winterwight','','17','undead','cold,lands','Bestiary 2',false],
['Witchfire','','9','undead','swamps,forests','Bestiary 2',false],
['Witchwyrd','','6','monstrous humanoid','lands','Bestiary 2',false],
['Worm That Walks','conjurer 13','14','vermin','any','Bestiary 2',false],
['Yrthak','','9','magical beast','deserts,hills,mountains','Bestiary 2',false],
['Human Juju Zombie','rogue 2','2','undead','lands','Bestiary 2',false]
];