//Name|Class|CR|Type|Terrain|Book/Page|isUnique
// 0 	== 1/2 CR
// -1 	== 1/3 CR
// -2	== 1/4 CR
// -3	== 1/6 CR
// -4	== 1/8 CR

var dmgnpc = [
["Foot Soldier","human warrior 1","-1","humanoid","Any","GameMastery Guide",false],
["Squire","human aristocrat 1","-1","humanoid","Any","GameMastery Guide",false],
["Village Idiot","human commoner 1","-1","humanoid","Any","GameMastery Guide",false],
["Acolyte","human cleric 1","0","humanoid","Any","GameMastery Guide",false],
["Bandit","human warrior 2","0","humanoid","Any","GameMastery Guide",false],
["Barmaid","human commoner 2","0","humanoid","Any","GameMastery Guide",false],
["Farmer","human commoner 1/expert 1","0","humanoid","Any","GameMastery Guide",false],
["Pickpocket","human rogue 1","0","humanoid","Any","GameMastery Guide",false],
["Shipmate","human expert 1/warrior 1","0","humanoid","Any","GameMastery Guide",false],
["Beggar","human commoner 1/rogue 1","1","humanoid","Any","GameMastery Guide",false],
["Cannibal","human barbarian 2","1","humanoid","Any","GameMastery Guide",false],
["Caravan Guard","human fighter 2","1","humanoid","Any","GameMastery Guide",false],
["Doomsayer","human adept 3","1","humanoid","Any","GameMastery Guide",false],
["Drunkard","human commoner 1/warrior 2","1","humanoid","Any","GameMastery Guide",false],
["Guard","human warrior 3","1","humanoid","Any","GameMastery Guide",false],
["Initiate","human monk 2","1","humanoid","Any","GameMastery Guide",false],
["Prostitute","human expert 1/rogue 1","1","humanoid","Any","GameMastery Guide",false],
["Shopkeep","human expert 3","1","humanoid","Any","GameMastery Guide",false],
["Storyteller","human bard 2","1","humanoid","Any","GameMastery Guide",false],
["Street Thug","human fighter 1/rogue 1","1","humanoid","Any","GameMastery Guide",false],
["Vagabond","human commoner 2/warrior 1","1","humanoid","Any","GameMastery Guide",false],
["Burglar","human rogue 3","2","humanoid","Any","GameMastery Guide",false],
["Cultist","human cleric 3","2","humanoid","Any","GameMastery Guide",false],
["Wanderer","human bard 1/rogue 2","2","humanoid","Any","GameMastery Guide",false],
["Noble Scion","human aristocrat 4","2","humanoid","Any","GameMastery Guide",false],
["Prisoner","human expert 4","2","humanoid","Any","GameMastery Guide",false],
["Barkeep","human expert 4/warrior 1","3","humanoid","Any","GameMastery Guide",false],
["Dealer","human expert 1/rogue 3","3","humanoid","Any","GameMastery Guide",false],
["Guard Officer","human fighter 4","3","humanoid","Any","GameMastery Guide",false],
["Pilgrim","human commoner 5","3","humanoid","Any","GameMastery Guide",false],
["Slaver","human fighter 2/ranger 2","3","humanoid","Any","GameMastery Guide",false],
["Trapper","human ranger 4","3","humanoid","Any","GameMastery Guide",false],
["Turnkey","human warrior 5","3","humanoid","Any","GameMastery Guide",false],
["Battle Monk","human monk 5","4","humanoid","Any","GameMastery Guide",false],
["Hedge wizard","human commoner 2/wizard 3","4","humanoid","Any","GameMastery Guide",false],
["Medium","human cleric 5","4","humanoid","Any","GameMastery Guide",false],
["Battle Mage","human evoker 6","5","humanoid","Any","GameMastery Guide",false],
["Cavalry","human fighter 6","5","humanoid","Any","GameMastery Guide",false],
["Fortune Teller","human bard 3/sorcerer 3","5","humanoid","Any","GameMastery Guide",false],
["Gladiator","human barbarian 3/fighter 3","5","humanoid","Any","GameMastery Guide",false],
["Minstrel","human bard 6","5","humanoid","Any","GameMastery Guide",false],
["Monster Hunter","human ranger 6","5","humanoid","Any","GameMastery Guide",false],
["Raider","human barbarian 6","5","humanoid","Any","GameMastery Guide",false],
["Shaman","human adept 7","5","humanoid","Any","GameMastery Guide",false],
["Tomb Raider","human rogue 6","5","humanoid","Any","GameMastery Guide",false],
["Torturer","human expert 5/fighter 2","5","humanoid","Any","GameMastery Guide",false],
["Traveling Merchant","human expert 7","5","humanoid","Any","GameMastery Guide",false],
["Archaeologist","human rogue 7","6","humanoid","Any","GameMastery Guide",false],
["Beast Master","human ranger 7","6","humanoid","Any","GameMastery Guide",false],
["Conjurist","human conjurer 7","6","humanoid","Any","GameMastery Guide",false],
["Hermit","human druid 7","6","humanoid","Any","GameMastery Guide",false],
["Highwayman","human fighter 4/rogue 3","6","humanoid","Any","GameMastery Guide",false],
["Holy warrior","human paladin 7","6","humanoid","Any","GameMastery Guide",false],
["Princess","human aristocrat 8","6","humanoid","Any","GameMastery Guide",false],
["Watch Captain","human fighter 7","6","humanoid","Any","GameMastery Guide",false],
["Guide","human expert 9","7","humanoid","Any","GameMastery Guide",false],
["Knight","human aristocrat 2/paladin 6","7","humanoid","Any","GameMastery Guide",false],
["Sellsword","human fighter 8","7","humanoid","Any","GameMastery Guide",false],
["Viking","human barbarian 2/fighter 6","7","humanoid","Any","GameMastery Guide",false],
["First Mate","human expert 4/fighter 5","8","humanoid","Any","GameMastery Guide",false],
["Mayor","human aristocrat 3/expert 7","8","humanoid","Any","GameMastery Guide",false],
["Noble","human aristocrat 10","8","humanoid","Any","GameMastery Guide",false],
["Priest","human cleric 9","8","humanoid","Any","GameMastery Guide",false],
["Slayer","human ranger 5/assassin 4","8","humanoid","Any","GameMastery Guide",false],
["Champion","human barbarian 5/fighter 5","9","humanoid","Any","GameMastery Guide",false],
["Merchant Prince","human expert 4/rogue 6","9","humanoid","Any","GameMastery Guide",false],
["Celebrity bard","human bard 11","10","humanoid","Any","GameMastery Guide",false],
["Chieftain","human warrior 12","10","humanoid","Any","GameMastery Guide",false],
["General","human fighter 11","10","humanoid","Any","GameMastery Guide",false],
["Guild Master","human rogue 11","10","humanoid","Any","GameMastery Guide",false],
["Queen","human aristocrat 12","10","humanoid","Any","GameMastery Guide",false],
["Bandit Lord","human fighter 8/rogue 4","11","humanoid","Any","GameMastery Guide",false],
["Bounty Hunter","human ranger 12","11","humanoid","Any","GameMastery Guide",false],
["Captain","human expert 3/fighter 9","11","humanoid","Any","GameMastery Guide",false],
["Cult Leader","human cleric 10/rogue 2","11","humanoid","Any","GameMastery Guide",false],
["Pirate Captain","human fighter 7/rogue 5","11","humanoid","Any","GameMastery Guide",false],
["Sage","human expert 7/abjurer 5","11","humanoid","Any","GameMastery Guide",false],
["Saint","human paladin 12","11","humanoid","Any","GameMastery Guide",false],
["High Priest","human  cleric 13","12","humanoid","Any","GameMastery Guide",false],
["King","human aristocrat 16","14","humanoid","Any","GameMastery Guide",false],
["Master","human monk 15","14","humanoid","Any","GameMastery Guide",false]
];