//Name|Class|CR|Type|Terrain|Book/Page|isU0nique
// 0 	== 1/2 CR
// -1 	== 1/3 CR
// -2	== 1/4 CR
// -3	== 1/6 CR
// -4	== 1/8 CR

var trap = [
['Arrrow Trap','','1','trap','any','Core Rulebook',false],
['Pit Trap','','1','trap','any','Core Rulebook',false],
['Poisoned Dart Trap','','1','trap','any','Core Rulebook',false],
['Swinging Axe Trap','','1','trap','any','Core Rulebook',false],
['Buring Hands Trap','','2','trap','any','Core Rulebook',false],
['Javelin Trap','','2','trap','any','Core Rulebook',false],
['Spiked Pit Trap','','2','trap','any','Core Rulebook',false],
['Acid Arrow Trap','','3','trap','any','Core Rulebook',false],
['Camouflaged Pit Trap','','3','trap','any','Core Rulebook',false],
['Electricity Arc Trap','','4','trap','any','Core Rulebook',false],
['Wall Scythe Trap','','4','trap','any','Core Rulebook',false],
['Falling Block Trap','','5','trap','any','Core Rulebook',false],
['Fireball Trap','','5','trap','any','Core Rulebook',false],
['Flame Strike Trap','','6','trap','any','Core Rulebook',false],
['Wyvern Arrow Trap','','6','trap','any','Core Rulebook',false],
['Frost Fangs Trap','','7','trap','any','Core Rulebook',false],
['Summon Monster VI Trap','','7','trap','any','Core Rulebook',false],
['Camouflaged Spiked Pit Trap','','8','trap','any','Core Rulebook',false],
['Insanity Mist Trap','','8','trap','any','Core Rulebook',false],
['Hail of Arrows Trap','','9','trap','any','Core Rulebook',false],
['Shocking Floor Trap','','9','trap','any','Core Rulebook',false],
['Energy Drain Trap','','10','trap','any','Core Rulebook',false],
['Chamber of Blades Trap','','10','trap','any','Core Rulebook',false],
['Cone of Cold Trap','','11','trap','any','Core Rulebook',false],
['Poisoned Pit Trap','','12','trap','any','Core Rulebook',false],
['Maximized Fireball Trap','','13','trap','any','Core Rulebook',false],
['Harm Trap','','14','trap','any','Core Rulebook',false],
['Crushing Stone Trap','','15','trap','any','Core Rulebook',false],
['Empowered Disintegrate Trap','','16','trap','any','Core Rulebook',false],
['Lightning Bolt Gallery Trap','','17','trap','urban,ruins','Core Rulebook',false],
['Deadly Spear Trap','','18','trap','any','Core Rulebook',false],
['Meteor Swarm Trap','','19','trap','any','Core Rulebook',false],
['Destruction Trap','','20','trap','any','Core Rulebook',false],
['Breakaway Vine','','1','trap','forests,jungles,swamps','Ultimate Wilderness',false],
['Musk Shower','','1','trap','any','Ultimate Wilderness',false],
['Spring Snare','','1','trap','forests,jungles,swamps','Ultimate Wilderness',false],
['Swinging Log','','1','trap','forests,jungles','Ultimate Wilderness',false],
['Tar Snare','','1','trap','any','Ultimate Wilderness',false],
['Clam Clamp','','2','trap','oceans,coastlines','Ultimate Wilderness',false],
['Razor Grass','','3','trap','plains,forests,jungles,swamps','Ultimate Wilderness',false],
['Breakaway Log','','4','trap','forests,swamps,jungles','Ultimate Wilderness',false],
['Spring-Arm Spike','','4','trap','forests,swamps,jungles','Ultimate Wilderness',false],
['Deadfall','','5','trap','forests,swamps,mountains,underground','Ultimate Wilderness',false],
['Dragonfire Trap','','1','trap','underground,forests','Monster Codex',false],
['Ensnaring Dirt Trap','','1','trap','underground,forests','Monster Codex',false],
['Acid Drop Trap','','2','trap','underground,forests','Monster Codex',false],
['Dragon Dung Pit Trap','','2','trap','underground,forests','Monster Codex',false],
['Falling Log Trap','','3','trap','underground,forests','Monster Codex',false],
['Snake Spear Trap','','3','trap','underground,forests','Monster Codex',false],
['Rotting Badger under a Falling Rock Trap','','4','trap','underground,forests','Monster Codex',false]
];

var haunt = [
['Spawn of the Abyss','','11','haunt','any','Horror Adventures',false],
['Whisper from Beyond','','10','haunt','any','Horror Adventures',false],
['Arcane Storm','','6','haunt','any','Horror Adventures',false],
['Psychic Echo','','10','haunt','any','Horror Adventures',false],
['Bloody Handprints','','-2','haunt','any','Horror Adventures',false],
['Scratching Behind the Wall','','0','haunt','urban','Horror Adventures',false],
['Cold Spot','','1','haunt','any','Horror Adventures',false],
['Spectral Screams','','2','haunt','any','Horror Adventures',false],
['Foreboding Mist','','3','haunt','any','Horror Adventures',false],
['Buried Alive','','4','haunt','any','Horror Adventures',false],
['Belated Arrival','','5','haunt','any','Horror Adventures',false],
['Unsolved Murder','','6','haunt','any','Horror Adventures',false],
['Betrayal','','7','haunt','any','Horror Adventures',false],
['Watery Grave','','8','haunt','lakes,rivers,oceans,coastlines','Horror Adventures',false],
['Devouring Maws','','9','haunt','any','Horror Adventures',false],
['Living Decay','','10','haunt','any','Horror Adventures',false],
['Eternal Pyre','','11','haunt','any','Horror Adventures',false],
['Dissolving Vat','','12','haunt','any','Horror Adventures',false],
['Heart Explosion','','13','haunt','urban','Horror Adventures',false],
['Crushing Terror','','14','haunt','any','Horror Adventures',false],
['Final Soldier','','15','haunt','any','Horror Adventures',false],
['Fallen from the Sky','','16','haunt','any','Horror Adventures',false],
['Haunted Dungeon','','17','haunt','urban,ruins','Horror Adventures',false],
['Flayed Suicide','','18','haunt','any','Horror Adventures',false],
['Soul Vortex','','19','haunt','any','Horror Adventures',false],
['Twisted Wish','','20','haunt','any','Horror Adventures',false],
['Bleeding Walls','','5','haunt','urban','GameMastery Guide',false]
];

var hazard = [
['Ear Seekers','','5','hazard','any','GameMastery Guide',false],
['Accursed Pool','','3','hazard','any','GameMastery Guide',false],
['Bad Air','','1','hazard','any','GameMastery Guide',false],
['Bad Air','','4','hazard','any','GameMastery Guide',false],
['Dweomersink','','6','hazard','any','GameMastery Guide',false],
['Magnetized Ore','','2','hazard','any','GameMastery Guide',false],
['Mnemonic Crystals','','3','hazard','any','GameMastery Guide',false],
['Poison Oak','','1','hazard','any','GameMastery Guide',false],
['Poison Oak','','3','hazard','any','GameMastery Guide',false],
['Rot Grubs','','4','hazard','any','GameMastery Guide',false],
['Cave-In','','8','hazard','urban,ruins,underground','Core Rulebook',false],
['Collapses','','4','hazard','urban,ruins,underground,hills,mountains','Core Rulebook',false],
['Avalanches','','7','hazard','hills,mountains','Core Rulebook',false],
['Brambles','','1','hazard','forests,swamps,ruins','Ultimate Wilderness',false],
['Earthquake','','9','hazard','any','Ultimate Wilderness',false],
['Acidic Miasma','','3','hazard','any','Ultimate Wilderness',false],
['Acidic Plants','','3','hazard','forests,swamps,marshes,plains','Ultimate Wilderness',false],
['Electrified Duststorm','','5','hazard','deserts,plains','Ultimate Wilderness',false],
['Fire Strom','','5','hazard','any','Ultimate Wilderness',false],
['Freezing Eruption','','5','hazard','any','Ultimate Wilderness',false],
['Fording a River','','2','hazard','rivers','Ultimate Wilderness',false],
['Fumarole','','1','hazard','any','Ultimate Wilderness',false],
['Geyser','','1','hazard','any','Ultimate Wilderness',false],
['Hot Spring','','2','hazard','any','Ultimate Wilderness',false],
['Mud Pot','','1','hazard','any','Ultimate Wilderness',false],
['Reflective Snow','','2','hazard','any','Ultimate Wilderness',false],
['Spellgorging Plants','','1','hazard','any','Ultimate Wilderness',false],
['Thin Ice','','1','hazard','rivers,coastlines,lakes','Ultimate Wilderness',false],
['Vampire Orchids','','3','hazard','forests,hills,plains','Ultimate Wilderness',false],
['Minor Lahar','','9','hazard','hills,mountains','Ultimate Wilderness',false],
['Lahar','','10','hazard','hills,mountains','Ultimate Wilderness',false],
['Massive Lahar','','12','hazard','hills,mountains','Ultimate Wilderness',false]
];