//Name|Class|CR|Type|Terrain|Book/Page|isUnique
// 0 	== 1/2 CR
// -1 	== 1/3 CR
// -2	== 1/4 CR
// -3	== 1/6 CR
// -4	== 1/8 CR

var monstercodex = [
['Boggard Brute','fighter 1','3','humanoid','marshes,jungles','Monster Codex',false],
['Boggard Champion','fighter 5','7','humanoid','marshes,jungles','Monster Codex',false],
['Boggard Farcroaker','bard 2','3','humanoid','marshes,jungles','Monster Codex',false],
['Boggard Abyssal Warrior','antipaladin 7','8','humanoid','marshes,jungles','Monster Codex',false],
['Boggard Savage','barbarian 2','4','humanoid','marshes,jungles','Monster Codex',false],
['Boggard Scarred One','barbarian 4','6','humanoid','marshes,jungles','Monster Codex',false],
['Boggard Swampseer','druid 3','4','humanoid','marshes,jungles','Monster Codex',false],
['Boggard Prophet','sorcerer 4','5','humanoid','marshes,jungles','Monster Codex',false],
['Boggard Hunter','ranger 3','5','humanoid','marshes,jungles','Monster Codex',false],
['Boggard Stalker','ranger 7','9','humanoid','marshes,jungles','Monster Codex',false],
['Boggard Priest-King','cleric 10','11','humanoid','marshes,jungles','Monster Codex',false],
['Bogwiggle','','1','aberrration','swamps','Monster Codex',false],
['Bugbear Gnasher','barbarian 2','4','humanoid','mountains','Monster Codex',false],
['Bugbear Flesh Glutton','barbarian 5','4','humanoid','mountains','Monster Codex',false],
['Bugbear Stalker','ranger 3','5','humanoid','mountains','Monster Codex',false],
['Bugbear Ambusher','ranger (trapper) 8','10','humanoid','mountains','Monster Codex',false],
['Bugbear Cultist','oracle 6','7','humanoid','mountains','Monster Codex',false],
['Bugbear Lurker','rogue 7','8','humanoid','mountains','Monster Codex',false],
['Bugbear Shadow Sneak','ninja 5\/shadowdancer 4','10','humanoid','mountains','Monster Codex',false],
['Bugbear Bloodmage','sorcerer','11','humanoid','mountains','Monster Codex',false],
['Bugbear Tyrant','antipaladin (fearmonger) 12','13','humanoid','mountains','Monster Codex',false],
['Frightful Haunter','','8','undead','any','Monster Codex',false],
['Drow Scout','rogue 2','1','humanoid','any,underground','Monster Codex',false],
['Drow Master Scout','rogue (sniper) 8','7','humanoid','any,underground','Monster Codex',false],
['Drow House Guard','fighter 3','2','humanoid','any,underground','Monster Codex',false],
['Drow House Captain','fighter 7','6','humanoid','any,underground','Monster Codex',false],
['Drow Priest','cleric 5','5','humanoid','any,underground','Monster Codex',false],
['Drow Demonic Champion','antipaladin 10','9','humanoid','any,underground','Monster Codex',false],
['Drow Poisoner','alchemist 12','11','humanoid','any,underground','Monster Codex',false],
['Drow Matron','cleric (demonic apostle) 15','15','humanoid','any,underground','Monster Codex',false],
['Abrakarn Viper','','13','construct','any,lands','Monster Codex',false],
['Duergar Sharpshooter','ranger 1','0','humanoid','any,underground','Monster Codex',false],
['Duergar Lieutenant','ranger 6','5','humanoid','any,underground','Monster Codex',false],
['Duergar Slaver','rogue 1','0','humanoid','any,underground','Monster Codex',false],
['Duergar Taskmaster','rogue 6 - shadowdancer 4','9','humanoid','any,underground','Monster Codex',false],
['Duergar Bombarier','alchemist 2','1','humanoid','any,underground','Monster Codex',false],
['Duergar Anvil','monk 2','1','humanoid','any,underground','Monster Codex',false],
['Duergar Hammer','monk (gray disciple) 12','11','humanoid','any,underground','Monster Codex',false],
['Duergar Sergant','fighter 2','1','humanoid','any,underground','Monster Codex',false],
['Duergar Captain','fighter 9','8','humanoid','any,underground','Monster Codex',false],
['Duergar High Priest','cleric 13','12','humanoid','any,underground','Monster Codex',false],
['Dark Spitter Beetle','','3','vermin','any,underground','Monster Codex',false],
['Fire Giant Glaive','fighter (polearm master) 2','12','humanoid','mountains','Monster Codex',false],
['Fire Giant Strongarm','fighter 3','13','humanoid','mountains','Monster Codex',false],
['Fire Giant Lieutenant','cavalier 6','16','humanoid','mountains','Monster Codex',false],
['Fire Giant Magmablade','magus 14','17','humanoid','mountains','Monster Codex',false],
['Fire Giant Doombringer','oracle 16','18','humanoid','mountains','Monster Codex',false],
['Fire Giant Queen','fighter 5\/sorcerer 8','19','humanoid','mountains','Monster Codex',false],
['Fire Giant King','ranger 10','20','humanoid','mountains','Monster Codex',false],
['Steam Hog','','7','magical beast','mountains','Monster Codex',false],
['Frost Giant Raider','barbarian 2','11','humanoid','cold,mountains','Monster Codex',false],
['Frost Giant Hunter','ranger 2','11','humanoid','cold,mountains','Monster Codex',false],
['Frost Giant Elite Scout','ranger 4','13','humanoid','cold,mountains','Monster Codex',false],
['Frost Giant Ice Mage','sorcerer 6','12','humanoid','cold,mountains','Monster Codex',false],
['Frost Giant Battle Priest','cleric 8','13','humanoid','cold,mountains','Monster Codex',false],
['Frost Giant Houndmaster','druid (artic druid) 10','14','humanoid','cold,mountains','Monster Codex',false],
['Frost Giant Jarl','ranger 9','18','humanoid','cold,mountains','Monster Codex',false],
['Svathurm','','11','monsterous humanoid','cold,hills,plains,mountains','Monster Codex',false],
['Ghoul Creeper','rogue 3','3','undead','lands,ruins','Monster Codex',false],
['Ghoul Stalker','rogue 6','6','undead','lands,ruins','Monster Codex',false],
['Ghoul Huntsmaster','ranger 6','7','undead','lands,ruins','Monster Codex',false],
['Ghoul Commander','antipaladin 7','8','undead','lands,ruins','Monster Codex',false],
['Masked Murderer','bard (dirge bard) 8','8','undead','lands,urban','Monster Codex',false],
['Ancient Gravedigger','oracle 10','10','undead','lands,ruins','Monster Codex',false],
['Ghoul Monarch','sorcerer 12','12','undead','lands,ruins','Monster Codex',false],
['Sootwing Bat','','0','undead','lands','Monster Codex',false],
['Ghoul Hound','','1','undead','lands','Monster Codex',false],
['Gnoll Rageborn','barbarian (pack rager) 2','3','humanoid','plains,deserts','Monster Codex',false],
['Gnoll Packlord','barbarian (pack rager) 8','9','humanoid','plains,deserts','Monster Codex',false],
['Gnoll Bruiser','fighter 1\/rogue 1','3','humanoid','plains,deserts','Monster Codex',false],
['Gnoll Warden','ranger 9','10','humanoid','plains,deserts','Monster Codex',false],
['Gnoll Sergeant','ranger 3','4','humanoid','plains,deserts','Monster Codex',false],
['Gnoll Lieutenant','fighter 5','6','humanoid','plains,deserts','Monster Codex',false],
['Eye of Lamashtu','cleric 4','5','humanoid','plains,deserts','Monster Codex',false],
['Gnoll Ravager','antipaladin 10','11','humanoid','plains,deserts','Monster Codex',false],
['Chosen of Lamashtu','cleric 11','12','humanoid','plains,deserts','Monster Codex',false],
['Gnoll Bouda','witch (bouda) 12','13','humanoid','plains,deserts','Monster Codex',false],
['Flind','','3','humanoid','plains,deserts','Monster Codex',false],
['Goblin Outrider','ranger 2','1','humanoid','forests,plains','Monster Codex',false],
['Goblin Rider','ranger 6','5','humanoid','forests,plains','Monster Codex',false],
['Goblin Sneak','rogue 2','1','humanoid','forests,plains','Monster Codex',false],
['Goblin Firestarter','rogue 5','4','humanoid','forests,plains','Monster Codex',false],
['Goblin Commando','fighter 3','2','humanoid','forests,plains','Monster Codex',false],
['Goblin Chief','fighter 10','9','humanoid','forests,plains','Monster Codex',false],
['Goblin Vulture Pilot','alchemist (winged marauder) 4','3','humanoid','forests,plains','Monster Codex',false],
['Goblin Frog-Talker','witch 6','5','humanoid','forests,plains','Monster Codex',false],
['Goblin Stickylord','alchemist 7','6','humanoid','forests,plains','Monster Codex',false],
['Mutant Goblin','barbarian 3','3','humanoid','forests,plains','Monster Codex',false],
['Hobgoblin Battlefield Zealot','cleric 2\/fighter 1','2','humanoid','hills','Monster Codex',false],
['Hobgoblin Sergeant','fighter 3','2','humanoid','hills','Monster Codex',false],
['Hobgoblin Lieutenant','ranger 5','4','humanoid','hills','Monster Codex',false],
['Hobgoblin Forerunner','fighter 7','6','humanoid','hills','Monster Codex',false],
['Hobgoblin Bombardier','alchemist (grenadier) 8','7','humanoid','hills','Monster Codex',false],
['Hobgoblin Battle Priest','cleric 9','8','humanoid','hills','Monster Codex',false],
['Hobgoblin Paragon','monk 11','10','humanoid','hills','Monster Codex',false],
['Hobgoblin Commander','samurai 13','12','humanoid','hills','Monster Codex',false],
['Yzobu','','1','animal','cold,plains,hills','Monster Codex',false],
['Kobold Sniper','fighter 1','0','humanoid','underground,forests','Monster Codex',false],
['Kobold Blade','fighter 4','3','humanoid','underground,forests','Monster Codex',false],
['Kobold Scalecaster','sorcerer 1','0','humanoid','underground,forests','Monster Codex',false],
['Kobold Guilecaster','sorcerer 6','5','humanoid','underground,forests','Monster Codex',false],
['Kobold Monster Wrangler','cavalier 2','1','humanoid','underground,forests','Monster Codex',false],
['Kobold Battle Master','cavalier 7','6','humanoid','underground,forests','Monster Codex',false],
['Kobold Bomber','alchemist (alchemical trapper) 2','1','humanoid','underground,forests','Monster Codex',false],
['Kobold Master Trapper','rogue 5','4','humanoid','underground,forests','Monster Codex',false],
['Kobold Devilspeaker','cleric 8','7','humanoid','underground,forests','Monster Codex',false],
['Kobold Yapper','bard (dragon yapper) 8','7','humanoid','underground,forests','Monster Codex',false],
['Kobold Chieftain','fighter 5\/rogue 3\/assassin 1','8','humanoid','underground,forests','Monster Codex',false],
['Kyrana','','3','dragon','underground,deserts','Monster Codex',false],
['Lizardfolk Vanguard','barbarian 1','2','humanoid','swamps','Monster Codex',false],
['Lizardfolk Berserker','barbarian 4','5','humanoid','swamps','Monster Codex',false],
['Lizardfolk Stalker','ranger 2','3','humanoid','swamps','Monster Codex',false],
['Lizardfolk Swamp Lurker','ranger 7','8','humanoid','swamps','Monster Codex',false],
['Lizardfolk Rattler','bard 4','5','humanoid','swamps','Monster Codex',false],
['Lizardfolk Champion','cavalier 9','10','humanoid','swamps','Monster Codex',false],
['Lizardfolk Sorcerer','sorcerer 11','12','humanoid','swamps','Monster Codex',false],
['Lizardfolk Clutch Mother','druid (ancient guardian) 12','13','humanoid','swamps','Monster Codex',false],
['Lizardfolk Scion','','5','humanoid','swamps','Monster Codex',false],
['Ogre Priest','cleric 2','4','humanoid','cold,hills','Monster Codex',false],
['Ogre Stalker','rogue 3','4','humanoid','cold,hills','Monster Codex',false],
['Ogre Brute','barbarian 3','6','humanoid','cold,hills','Monster Codex',false],
['Ogre Boss','fighter 4','7','humanoid','cold,hills','Monster Codex',false],
['Ogre Mancather','fighter 5','8','humanoid','cold,hills','Monster Codex',false],
['Ogre Glutton','barbarian 8','11','humanoid','cold,hills','Monster Codex',false],
['Ogre Hunter','ranger 6','9','humanoid','cold,hills','Monster Codex',false],
['Ogre Destroyer','antipaladin 7','10','humanoid','cold,hills','Monster Codex',false],
['Ogre King','oracle 12','13','humanoid','cold,hills','Monster Codex',false],
['Troggle','','4','humanoid','cold,hills,mountains','Monster Codex',false],
['Troggle Raider','ranger 2','6','humanoid','cold,hills,mountains','Monster Codex',false],
['Orc Sergeant','fighter 3','2','humanoid','hills,mountains,underground','Monster Codex',false],
['Orc Lieutenant','fighter 5','4','humanoid','hills,mountains,underground','Monster Codex',false],
['Orc Mystic','cleric 3','2','humanoid','hills,mountains,underground','Monster Codex',false],
['Orc Thug','rogue 4','3','humanoid','hills,mountains,underground','Monster Codex',false],
['Orc War Drummer','bard (savage skald) 4','3','humanoid','hills,mountains,underground','Monster Codex',false],
['Orc Scout','ranger 6','5','humanoid','hills,mountains,underground','Monster Codex',false],
['Gorthek Rider','cavalier 7','6','humanoid','hills,mountains,underground','Monster Codex',false],
['Orc Warlord','barbarian 7','6','humanoid','hills,mountains,underground','Monster Codex',false],
['Orc Chieftan','fighter 10','9','humanoid','hills,mountains,underground','Monster Codex',false],
['Orc Witch Docter','witch (scarred witch docter) 9','8','humanoid','hills,mountains,underground','Monster Codex',false],
['Gorthek','','7','animal','hills,plains','Monster Codex',false],
['Ratfolk Tinkerer','rogue 2','1','humanoid','deserts,urban','Monster Codex',false],
['Ratfolk Troubleshooter','rogue 6','5','humanoid','deserts,urban','Monster Codex',false],
['Ratfolk Bravo','gunslinger 3','2','humanoid','deserts,urban','Monster Codex',false],
['Ratfolk Warden','fighter 5','4','humanoid','deserts,urban','Monster Codex',false],
['Ratfolk Caravan Guard','ranger 4','3','humanoid','deserts,urban','Monster Codex',false],
['Ratfolk Expedition Leader','ranger 8','7','humanoid','deserts,urban','Monster Codex',false],
['Ratfolk Sage','diviner 7','6','humanoid','deserts,urban','Monster Codex',false],
['Ratfolk Chemist','alchemist 8','7','humanoid','deserts,urban','Monster Codex',false],
['Ratfolk Elder','cleric 9','8','humanoid','deserts,urban','Monster Codex',false],
['Kirrix','','3','magical beast','underground','Monster Codex',false],
['Sahuagin Scout','rogue 2','3','monstrous humanoid','oceans','Monster Codex',false],
['Sahuagin Infiltrator','rogue 6','7','monstrous humanoid','oceans','Monster Codex',false],
['Sahuagin Brute','barbarian 1','3','monstrous humanoid','oceans','Monster Codex',false],
['Sahuagin Champion','barbarian 7','10','monstrous humanoid','oceans','Monster Codex',false],
['Sahuagin Deep Racer','ranger 2','4','monstrous humanoid','oceans','Monster Codex',false],
['Sahuagin Shark Sentry','ranger 4','6','monstrous humanoid','oceans','Monster Codex',false],
['Sahuagin Underpriestess','cleric 4','5','monstrous humanoid','oceans','Monster Codex',false],
['Sahuagin High Priestess','cleric 7','9','monstrous humanoid','oceans','Monster Codex',false],
['Sahuagin Lieutenant','fighter 3','5','monstrous humanoid','oceans','Monster Codex',false],
['Sahuagin Baron','fighter 7','9','monstrous humanoid','oceans','Monster Codex',false],
['Sahuagin Prince','cavalier (beast rider) 10','13','monstrous humanoid','oceans','Monster Codex',false],
['Feeder in the Depths','','8','magical beast','oceans','Monster Codex',false],
['Serpentfolk Spy','rogue 1','5','monstrous humanoid','lands','Monster Codex',false],
['Serpentfolk Hunter','ranger 2','6','monstrous humanoid','lands','Monster Codex',false],
['Serpentfolk Illusionist','illusionist 4','8','monstrous humanoid','lands','Monster Codex',false],
['Serpentfolk Bone Prophet','oracle 7','11','monstrous humanoid','lands','Monster Codex',false],
['Serpentfolk Spellblade','magus 9','13','monstrous humanoid','lands','Monster Codex',false],
['Serpentfolk High Priest','cleric 10','14','monstrous humanoid','lands','Monster Codex',false],
['Seru','','3','magical beast','jungles,swamps,underground','Monster Codex',false],
['Troll Acolyte','cleric 2','6','humanoid','cold,mountains','Monster Codex',false],
['Troll Warden','ranger 2','6','humanoid','cold,mountains','Monster Codex',false],
['Troll Brute','barbarian 2','7','humanoid','cold,mountains','Monster Codex',false],
['Troll Berserker','barbarian 4','9','humanoid','cold,mountains','Monster Codex',false],
['Troll Ripper','fighter 3','8','humanoid','cold,mountains','Monster Codex',false],
['Troll Render','fighter 5','10','humanoid','cold,mountains','Monster Codex',false],
['Troll Fury','druid (troll fury) 6','8','humanoid','cold,mountains','Monster Codex',false],
['Troll Elder Matron','witch 10','10','humanoid','cold,mountains','Monster Codex',false],
['Troll Monarch','fighter 10','15','humanoid','cold,mountains','Monster Codex',false],
['Sewer Troll','','2','humanoid','underground,urban','Monster Codex',false],
['Coffin Guard','elf ranger 4','3','humanoid','urban,underground,ruins','Monster Codex',false],
['Weird Butler','halfing oracle 5','4','humanoid','urban,underground,ruins','Monster Codex',false],
['Vampire Seducer','human vampire bard 5','6','undead','urban,underground,ruins','Monster Codex',false],
['Vampire Warrior','vishkanya jiang-shi fighter 7','8','undead','urban,underground,ruins','Monster Codex',false],
['Vampire Savage','half-orc vampire barbarian 9','10','undead','urban,underground,ruins','Monster Codex',false],
['Enlightened Vampire','human vampire monk (hungry ghost monk) 11','12','undead','urban,underground,ruins','Monster Codex',false],
['Vampire Lord','half-elf vampire magus 14','15','undead','urban,underground,ruins','Monster Codex',false],
['Vampire Spawn','human rogue 2','2','undead','urban,underground,ruins','Monster Codex',false]
];