//Name|Class|CR|Type|Terrain|Book/Page|isUnique
// 0 	== 1/2 CR
// -1 	== 1/3 CR
// -2	== 1/4 CR
// -3	== 1/6 CR
// -4	== 1/8 CR

var npccodex = [
['Savage Mercenary','human barbarian 1','0','humanoid','any','NPC Codex',false],
['Dwarven Rager','dwarf barbarian 2','1','humanoid','any','NPC Codex',false],
['Axe Warrior','half-orc barbarian 3','2','humanoid','any','NPC Codex',false],
['Dog Rider','halfling barbarian 4','3','humanoid','any','NPC Codex',false],
['Wild Lancer','half-elf barbarian 5','4','humanoid','any','NPC Codex',false],
['Forest Guardian','elf barbarian 6','5','humanoid','any','NPC Codex',false],
['Sundering Axe','dwarf barbarian 7','6','humanoid','any','NPC Codex',false],
['Glaive Rager','gnome barbarian 8','7','humanoid','any','NPC Codex',false],
['Raging Swimmer','half-elf barbarian 9','8','humanoid','any','NPC Codex',false],
['Cannibalistic Hunter','halfling barbarian 10','9','humanoid','any','NPC Codex',false],
['Double Axe Fury','half-orc barbarian 11','10','humanoid','any','NPC Codex',false],
['Giant Slayer','dwarf barbarian 12','11','humanoid','any','NPC Codex',false],
['Savage Rider','human barbarian 13','12','humanoid','any','NPC Codex',false],
['Arcane Experimenter','gnome barbarian 14','13','humanoid','any','NPC Codex',false],
['Life Stealer','human barbarian 15','14','humanoid','any','NPC Codex',false],
['Undead Hunter','half-orc barbarian 16','15','humanoid','any','NPC Codex',false],
['Graceful Slayer','elf barbarian 17','16','humanoid','any','NPC Codex',false],
['Refined Reaver','human barbarian 18','17','humanoid','any','NPC Codex',false],
['Death Dealer','half-orc barbarian 19','18','humanoid','any','NPC Codex',false],
['Scarred Wanderer','dwarf barbarian 20','19','humanoid','any','NPC Codex',false],
['Tavern Singer','half-elf bard 1','0','humanoid','any','NPC Codex',false],
['Street Performer','human bard 2','1','humanoid','any','NPC Codex',false],
['Local Celebrity','human bard 3','2','humanoid','any','NPC Codex',false],
['Taunting Comedian','halfling bard 4','3','humanoid','any','NPC Codex',false],
['Court Poet','human bard 5','4','humanoid','any','NPC Codex',false],
['Con Artist','half-elf bard 6','5','humanoid','any','NPC Codex',false],
['Gambler','dwarf bard 7','6','humanoid','any','NPC Codex',false],
['Street Artist','elf bard 8','7','humanoid','any','NPC Codex',false],
['Cruel Instructor','human bard 9','8','humanoid','any','NPC Codex',false],
['Seance Medium','human bard 10','9','humanoid','any','NPC Codex',false],
['Chameleon','half-orc bard 11','10','humanoid','any','NPC Codex',false],
['Courtesan','human bard 12','11','humanoid','any','NPC Codex',false],
['Tribal Leader','human bard 13','12','humanoid','any','NPC Codex',false],
['Tunnel Drummer','dwarf bard 14','13','humanoid','any','NPC Codex',false],
['Lion Tamer','gnome bard 15','14','humanoid','any','NPC Codex',false],
['Spellsword','elf bard 16','15','humanoid','any','NPC Codex',false],
['Notorious Foil','halfling bard 17','16','humanoid','any','NPC Codex',false],
['Rival Explorer','half-orc bard 18','17','humanoid','any','NPC Codex',false],
['Master Spy','human bard 19','18','humanoid','any','NPC Codex',false],
['Doomsayer','human bard 20','19','humanoid','any','NPC Codex',false],
['Mercenary Healer','human cleric 1','0','humanoid','any','NPC Codex',false],
['War Priest','dwarf cleric 2','1','humanoid','any','NPC Codex',false],
['Scholar Priest','human cleric 3','2','humanoid','any','NPC Codex',false],
['Shoreline Cleric','half-elf cleric 4','3','humanoid','any','NPC Codex',false],
['Noble Crusader','human cleric 5','4','humanoid','any','NPC Codex',false],
['Carousing Champion','halfling cleric 6','5','humanoid','any','NPC Codex',false],
['Vivisectionist Cleric','human cleric 7','6','humanoid','any','NPC Codex',false],
['Wrath Priest','half-orc cleric 8','7','humanoid','any','NPC Codex',false],
['Death Priest','human cleric 9','8','humanoid','any','NPC Codex',false],
['Mother of Beasts','human cleric 10','9','humanoid','any','NPC Codex',false],
['Fire Cleric','human cleric 11','10','humanoid','any','NPC Codex',false],
['Trickster Priest','human cleric 12','11','humanoid','any','NPC Codex',false],
['Profane General','human cleric 13','12','humanoid','any','NPC Codex',false],
['Sacred Guardian','gnome cleric 14','13','humanoid','any','NPC Codex',false],
['Master of Undead','human cleric 15','14','humanoid','any','NPC Codex',false],
['Elemental Priest','halfling cleric 16','15','humanoid','any','NPC Codex',false],
['Herald of Armageddon','human cleric 17','16','humanoid','any','NPC Codex',false],
['Shadow Cleric','elf cleric 18','17','humanoid','any','NPC Codex',false],
['Priest of Oblivion','human cleric 19','18','humanoid','any','NPC Codex',false],
['Fire Diabolist','human cleric 20','19','humanoid','any','NPC Codex',false],
['Initiate of Flame','dwarf druid 1','0','humanoid','any','NPC Codex',false],
['Sail Master','human druid 2','1','humanoid','any','NPC Codex',false],
['Sylvan Protector','gnome druid 3','2','humanoid','any','NPC Codex',false],
['Savage Plant Sage','half-orc druid 4','3','humanoid','any','NPC Codex',false],
['Cavern Defender','half-elf druid 5','4','humanoid','any','NPC Codex',false],
['Evasive Slip','halfling druid 6','5','humanoid','any','NPC Codex',false],
['Island Defender','elf druid 7','6','humanoid','any','NPC Codex',false],
['Sea Captain','halfling druid 8','7','humanoid','any','NPC Codex',false],
['Mud Shaman','human druid 9','8','humanoid','any','NPC Codex',false],
['Water Merchant','gnome druid 10','9','humanoid','any','NPC Codex',false],
['Mistress of High Places','half-elf druid 11','10','humanoid','any','NPC Codex',false],
['Castaway','half-orc druid 12','11','humanoid','any','NPC Codex',false],
['Fey Friend','gnome druid 13','12','humanoid','any','NPC Codex',false],
['Fury of Flame','human druid 14','13','humanoid','any','NPC Codex',false],
['Creeping Death','elf druid 15','14','humanoid','any','NPC Codex',false],
['Taiga Stalker','human druid 16','15','humanoid','any','NPC Codex',false],
['Hateful Scourge','half-elf druid 17','16','humanoid','any','NPC Codex',false],
['Dark Nature Priest','halfling druid 18','17','humanoid','any','NPC Codex',false],
['Rage Flame','half-orc druid 19','18','humanoid','any','NPC Codex',false],
['Earthfather','dwarf druid 20','19','humanoid','any','NPC Codex',false],
['Superstitious Mercenary','human fighter 1','0','humanoid','any','NPC Codex',false],
['Daring Bravo','gnome fighter 2','1','humanoid','any','NPC Codex',false],
['Traitorous Brigand','half-orc fighter 3','2','humanoid','any','NPC Codex',false],
['Murderous Halfling','halfling fighter 4','3','humanoid','any','NPC Codex',false],
['Cautious Archer','elf fighter 5','4','humanoid','any','NPC Codex',false],
['Adventuring Blacksmith','half-elf fighter 6','5','humanoid','any','NPC Codex',false],
['Spell Hunter','dwarf fighter 7','6','humanoid','any','NPC Codex',false],
['Fastidious Sharpshooter','gnome fighter 8','7','humanoid','any','NPC Codex',false],
['Halfling Slinger','halfling fighter 9','8','humanoid','any','NPC Codex',false],
['Griffon Rider','elf fighter 10','9','humanoid','any','NPC Codex',false],
['Scheming Fencer','human fighter 11','10','humanoid','any','NPC Codex',false],
['Shieldbreaker','dwarf fighter 12','11','humanoid','any','NPC Codex',false],
['Brutal Warlord','half-orc fighter 13','12','humanoid','any','NPC Codex',false],
['Arcane Pretender','halfling fighter 14','13','humanoid','any','NPC Codex',false],
['Pirate King','half-elf fighter 15','14','humanoid','any','NPC Codex',false],
['Dwarven Arbalester','dwarf fighter 16','15','humanoid','any','NPC Codex',false],
['Elven Recluse','elf fighter 17','16','humanoid','any','NPC Codex',false],
['Failed Disciple','half-orc fighter 18','17','humanoid','any','NPC Codex',false],
['Crime Lord','gnome fighter 19','18','humanoid','any','NPC Codex',false],
['Infernal Champion','human fighter 20','19','humanoid','any','NPC Codex',false],
['Careful Initiate','human monk 1','0','humanoid','any','NPC Codex',false],
['Bullying Brawler','human monk 2','1','humanoid','any','NPC Codex',false],
['Vigilant Bodyguard','human monk 3','2','humanoid','any','NPC Codex',false],
['Spry Ambusher','gnome monk 4','3','humanoid','any','NPC Codex',false],
['Cruel Devotee','human monk 5','4','humanoid','any','NPC Codex',false],
['Nimble Shuriken Thrower','halfling monk 6','5','humanoid','any','NPC Codex',false],
['Harrying Brute','human monk 7','6','humanoid','any','NPC Codex',false],
['Axe Dancer','half-orc monk 8','7','humanoid','any','NPC Codex',false],
['Steadfast Defender','dwarf monk 9','8','humanoid','any','NPC Codex',false],
['Cautious Hunter','half-orc monk 10','9','humanoid','any','NPC Codex',false],
['Poisonous Performer','human monk 11','10','humanoid','any','NPC Codex',false],
['Swift Brawler','human monk 12','11','humanoid','any','NPC Codex',false],
['Monastic Sniper','elf monk 13','12','humanoid','any','NPC Codex',false],
['Little Fist','halfling monk 14','13','humanoid','any','NPC Codex',false],
['Improvised Hurler','dwarf monk 15','14','humanoid','any','NPC Codex',false],
['Horse Monk','human monk 16','15','humanoid','any','NPC Codex',false],
['Warren Chief','gnome monk 17','16','humanoid','any','NPC Codex',false],
['Grove Guardian','half-elf monk 18','17','humanoid','any','NPC Codex',false],
['Sword Savant','elf monk 19','18','humanoid','any','NPC Codex',false],
['Ageless Master','human monk 20','19','humanoid','any','NPC Codex',false],
['Callous Rake','human paladin 1','0','humanoid','any','NPC Codex',false],
['Honorable Outcast','half-orc paladin 2','1','humanoid','any','NPC Codex',false],
['Haughty Avenger','half-elf paladin 3','2','humanoid','any','NPC Codex',false],
['Skirmishing Crusader','gnome paladin 4','3','humanoid','any','NPC Codex',false],
['Hammer of Justice','dwarf paladin 5','4','humanoid','any','NPC Codex',false],
['Holy Archer','elf paladin 6','5','humanoid','any','NPC Codex',false],
['Dog Rider Knight','halfling paladin 7','6','humanoid','any','NPC Codex',false],
['Desert Protector','human paladin 8','7','humanoid','any','NPC Codex',false],
['Saintly Knight','half-orc paladin 9','8','humanoid','any','NPC Codex',false],
['Pious Guard','human paladin 10','9','humanoid','any','NPC Codex',false],
['Elven Honorblade','elf paladin 11','10','humanoid','any','NPC Codex',false],
['Forge Rider','dwarf paladin 12','11','humanoid','any','NPC Codex',false],
['Dragon Master','human paladin 13','12','humanoid','any','NPC Codex',false],
['Rider of the Steppe','half-elf paladin 14','13','humanoid','any','NPC Codex',false],
['Giant Hunter','gnome paladin 15','14','humanoid','any','NPC Codex',false],
['Mounted Paragon','human paladin 16','15','humanoid','any','NPC Codex',false],
['Axe Lord','halfling paladin 17','16','humanoid','any','NPC Codex',false],
['Furious Crusader','halfling paladin 17','16','humanoid','any','NPC Codex',false],
['Mithral Master','half-elf paladin 19','18','humanoid','any','NPC Codex',false],
['Demon Hunter','human paladin 20','19','humanoid','any','NPC Codex',false],
['Novice Scout','half-elf ranger 1','0','humanoid','any','NPC Codex',false],
['Town Watcher','halfling ranger 2','1','humanoid','any','NPC Codex',false],
['Poacher','human ranger 3','2','humanoid','any','NPC Codex',false],
['Border Guard','half-orc ranger 4','3','humanoid','any','NPC Codex',false],
['Mounted Archer','human ranger 5','4','humanoid','any','NPC Codex',false],
['Tunnel Rat','human ranger 6','5','humanoid','any','NPC Codex',false],
['Mountaineer','dwarf ranger 7','6','humanoid','any','NPC Codex',false],
['Orc Slayer','elf ranger 8','7','humanoid','any','NPC Codex',false],
['Swampwalker','half-elf ranger 9','8','humanoid','any','NPC Codex',false],
['Pirate Queen','halfling ranger 10','9','humanoid','any','NPC Codex',false],
['Giant-Killer','gnome ranger 11','10','humanoid','any','NPC Codex',false],
['Bounty Hunter','human ranger 12','11','humanoid','any','NPC Codex',false],
['Fiendslayer','half-elf ranger 13','12','humanoid','any','NPC Codex',false],
['Desert Stalker','half-orc ranger 14','13','humanoid','any','NPC Codex',false],
['Angel Slayer','half-elf ranger 15','14','humanoid','any','NPC Codex',false],
['Undead Slayer','human ranger 16','15','humanoid','any','NPC Codex',false],
['Daredevil Hunter','elf ranger 17','16','humanoid','any','NPC Codex',false],
['Golem-Breaker','dwarf ranger 18','17','humanoid','any','NPC Codex',false],
['Mage Hunter','human ranger 19','18','humanoid','any','NPC Codex',false],
['Supreme Hunter','human ranger 20','19','humanoid','any','NPC Codex',false],
['Cutpurse','human rogue 1','0','humanoid','any','NPC Codex',false],
['Skulking Brute','half-orc rogue 2','1','humanoid','any','NPC Codex',false],
['Skilled Sniper','half-elf rogue 3','2','humanoid','any','NPC Codex',false],
['Charlatan','human rogue 4','3','humanoid','any','NPC Codex',false],
['Guild Initiate','halfling rogue 5','4','humanoid','any','NPC Codex',false],
['Cave Stalker','dwarf rogue 6','5','humanoid','any','NPC Codex',false],
['Freelance Thief','human rogue 7','6','humanoid','any','NPC Codex',false],
['Trapsmith','gnome rogue 8','7','humanoid','any','NPC Codex',false],
['Deadly Spy','elf rogue 9','8','humanoid','any','NPC Codex',false],
['Dancing Dervish','human rogue 10','9','humanoid','any','NPC Codex',false],
['Contact Killer','elf rogue 11','10','humanoid','any','NPC Codex',false],
['Dilettante','human rogue 12','11','humanoid','any','NPC Codex',false],
['Guildmaster','dwarf rogue 13','12','humanoid','any','NPC Codex',false],
['Chain Mauler','human rogue 14','13','humanoid','any','NPC Codex',false],
['Unseen Archer','half-elf rogue 15','14','humanoid','any','NPC Codex',false],
['Mage Slayer','half-orc rogue 16','15','humanoid','any','NPC Codex',false],
['Masked Lord','human rogue 17','16','humanoid','any','NPC Codex',false],
['Dagger Master','halfling rogue 18','17','humanoid','any','NPC Codex',false],
['Death Whisperer','human rogue 19','18','humanoid','any','NPC Codex',false],
['Blade Lord','elf rogue 20','19','humanoid','any','NPC Codex',false],
['Mercenary Magician','human sorcerer 1','0','humanoid','any','NPC Codex',false],
['Gem Sorcerer','dwarf sorcerer 2','1','humanoid','any','NPC Codex',false],
['Whiteclaw Sorcerer','elf sorcerer 3','2','humanoid','any','NPC Codex',false],
['Tainted Sorcerer','gnome sorcerer 4','3','humanoid','any','NPC Codex',false],
['Bramble Sorcerer','half-elf sorcerer 5','4','humanoid','any','NPC Codex',false],
['Strom Sorcerer','elf sorcerer 6','5','humanoid','any','NPC Codex',false],
['Bloodfire Sorcerer','half-orc sorcerer 7','6','humanoid','any','NPC Codex',false],
['Trickster Mage','gnome sorcerer 8','7','humanoid','any','NPC Codex',false],
['Sacred Sorcerer','human sorcerer 9','8','humanoid','any','NPC Codex',false],
['Blackscale Sorcerer','half-orc sorcerer 10','9','humanoid','any','NPC Codex',false],
['Lucky Mage','halfling sorcerer 11','10','humanoid','any','NPC Codex',false],
['Fey Enchantress','elf sorcerer 12','11','humanoid','any','NPC Codex',false],
['Azure Bolt Sorcerer','human sorcerer 13','12','humanoid','any','NPC Codex',false],
['Ice Mage','half-elf sorcerer 14','13','humanoid','any','NPC Codex',false],
['Diabolical Charmer','human sorcerer 15','14','humanoid','any','NPC Codex',false],
['Natural Arcanist','halfling sorcerer 16','15','humanoid','any','NPC Codex',false],
['Fiery Dragonkin','dwarf sorcerer 17','16','humanoid','any','NPC Codex',false],
['Demon-Blooded Sorcerer','half-orc sorcerer 18','17','humanoid','any','NPC Codex',false],
['Fate-Bound Mage','human sorcerer 19','18','humanoid','any','NPC Codex',false],
['Arisen Sorcerer','human sorcerer 20','19','humanoid','any','NPC Codex',false],
['Cautious Mage','human wizard 1','0','humanoid','any','NPC Codex',false],
['Street Magician','gnome enchanter 2','1','humanoid','any','NPC Codex',false],
['Battle Mage','elf wizard 3','2','humanoid','any','NPC Codex',false],
['Investigator Wizard','human diviner 4','3','humanoid','any','NPC Codex',false],
['Jungle Wizard','elf transmuter 5','4','humanoid','any','NPC Codex',false],
['Tribal Seer','half-orc diviner 6','5','humanoid','any','NPC Codex',false],
['Thunder Wizard','halfling evoker 7','6','humanoid','any','NPC Codex',false],
['Seductive Enchanter','elf enchanter 8','7','humanoid','any','NPC Codex',false],
['Cave Wizard','dwarf evoker 9','8','humanoid','any','NPC Codex',false],
['Prankster Illusionist','gnome illusionist 10','9','humanoid','any','NPC Codex',false],
['Undead Creator','human necromancer 11','10','humanoid','any','NPC Codex',false],
['Toothy Transmuter','half-orc transmuter 12','11','humanoid','any','NPC Codex',false],
['Pyromaniac Mage','human evoker 13','12','humanoid','any','NPC Codex',false],
['Mage Sniper','half-elf evoker 14','13','humanoid','any','NPC Codex',false],
['Cruel Conjurer','human conjurer 15','14','humanoid','any','NPC Codex',false],
['Deep Marshal','dwarf abjurer 16','15','humanoid','any','NPC Codex',false],
['Mage Spy','gnome wizard 17','16','humanoid','any','NPC Codex',false],
['Grand Necromancer','human necromancer 18','17','humanoid','any','NPC Codex',false],
['Puppet Master','half-elf enchanter 19','18','humanoid','any','NPC Codex',false],
['Master Universalist','elf wizard 20','19','humanoid','any','NPC Codex',false],
['Undead Bane','human ranger 9/sorcerer 1/arcane archer 7','16','humanoid','any','NPC Codex',false],
['Choas Arrow','gnome rogue6/sorcerer 1/arcane archer 10','19','humanoid','any','NPC Codex',false],
['Green Warden','elf fighter 5/conjurer 2/arcane archer 2','8','humanoid','any','NPC Codex',false],
['Tournament Champion','half-elf bard 7/sorcerer 2/arcane archer 4','12','humanoid','any','NPC Codex',false],
['Stage Magician','half-orc bard 4/rogue 3/arcane trickster 2','8','humanoid','any','NPC Codex',false],
['Arcanothief','halfling rogue 4/sorcerer 5/arcane trickster 4','12','humanoid','any','NPC Codex',false],
['Vaultbreaker','human rogue 6/transmuter 4/arcane trickster 7','16','humanoid','any','NPC Codex',false],
['God Stealer','elf rogue 4/enchanter 7/arcane trickster 10','19','humanoid','any','NPC Codex',false],
['Sacred Killer','half-elf cleric 1/rogue 6/assassin 2','8','humanoid','any','NPC Codex',false],
['Death Initiate','human monk 9/assassin 4','12','humanoid','any','NPC Codex',false],
['Murderous Scythe','half-elf druid 4/fighter 6/assassin 7','16','humanoid','any','NPC Codex',false],
['Fatal Axe','dwarf rogue 10/assassin 10','19','humanoid','any','NPC Codex',false],
['Storm Prophet','dwarf sorcerer 7/dragon disciple 2','8','humanoid','any','NPC Codex',false],
['Acid Terror','human sorcerer 9/dragon disciple 4','12','humanoid','any','NPC Codex',false],
['Dragon Chieftain','half-orc bard 10/dragon disciple 7','16','humanoid','any','NPC Codex',false],
['Ice Maiden','sorcerer 10/dragon disciple 10','19','humanoid','any','NPC Codex',false],
['Tribal Champion','half-elf fighter/duelist 2','8','humanoid','any','NPC Codex',false],
['Feisty Hotspur','halfling rogue 9/duelist 4','12','humanoid','any','NPC Codex',false],
['Iron Duelist','dwarf fighter 10/duelist 7','16','humanoid','any','NPC Codex',false],
['Master Duelist','human fighter 10/duelist 10','19','humanoid','any','NPC Codex',false],
['Queen of Staves','elf fighter 2/abjurer 5/eldritch knight 2','8','humanoid','any','NPC Codex',false],
['Champion of Magic','gnome paladin 2/sorcerer 7/eldritch knight 4','12','humanoid','any','NPC Codex',false],
['Spirit Avenger','half-orc barbarian 4/sorcerer 6/eldritch knight 7','16','humanoid','any','NPC Codex',false],
['Mithral Wizard','human fighter 2/evoker 8/eldritch knight 10','19','humanoid','any','NPC Codex',false],
['Divine Loremaster','halfling cleric 7/loremaster 2','8','humanoid','any','NPC Codex',false],
['Nature Scholar','elf druid 9/loremaster 4','12','humanoid','any','NPC Codex',false],
['Master Historian','dwarf bard 10/loremaster 7','16','humanoid','any','NPC Codex',false],
['Demonologist','human conjurer 10/loremaster 10','19','humanoid','any','NPC Codex',false],
['Celestial Theurge','human cleric 3/sorcerer 4/mystic theurge 2','8','humanoid','any','NPC Codex',false],
['Sound Warrior','halfling bard 5/druid 4/mystic theurge 4','12','humanoid','any','NPC Codex',false],
['Death Master','half-elf cleric 5/evoker 5/mystic theurge 7','16','humanoid','any','NPC Codex',false],
['Holy Battle Mage','dwarf cleric 5/wizard 5/mystic theurge 10','19','humanoid','any','NPC Codex',false],
['Aloof Scholar','human bard 7/pathfinder chronicler 2','8','humanoid','any','NPC Codex',false],
['Mad Prophet','gnome cleric 9/pathfinder chronicler 4','12','humanoid','any','NPC Codex',false],
['Master Storycrafter','half-elf sorcerer 10/pathfinder chronicler 7','16','humanoid','any','NPC Codex',false],
['Battle Skald','human barbarian 6/bard 4/pathfinder chronicler 10','19','humanoid','any','NPC Codex',false],
['Blackstrike','human fighter 7/shadowdancer 2','8','humanoid','any','NPC Codex',false],
['Midnight Dancer','half-orc bard 9/shadowdancer 4','12','humanoid','any','NPC Codex',false],
['Black Ice','gnome illusionist 10/shadowdancer 7','16','humanoid','any','NPC Codex',false],
['Darkstar','halfling rogue 10/shadowdancer 10','19','humanoid','any','NPC Codex',false],
['Acolyte','human adept 1','0','humanoid','any','NPC Codex',false],
['Shaman','half-orc adept 2','1','humanoid','any','NPC Codex',false],
['Initiate','human adept 3','2','humanoid','any','NPC Codex',false],
['Doom Prophet','half-orc adept 4','3','humanoid','any','NPC Codex',false],
['Enforcer','human adept 5','4','humanoid','any','NPC Codex',false],
['Guru','dwarf adept 6','5','humanoid','any','NPC Codex',false],
['Hermit','human adept 7','6','humanoid','any','NPC Codex',false],
['Heretic','half-elf adept 8','7','humanoid','any','NPC Codex',false],
['Healer','halfling adept 9','8','humanoid','any','NPC Codex',false],
['Cultist','human adept 10','9','humanoid','any','NPC Codex',false],
['Page','halfling aristocrat 1','0','humanoid','any','NPC Codex',false],
['Princess','human aristocrat 2','1','humanoid','any','NPC Codex',false],
['Squire','human aristocrat 3','2','humanoid','any','NPC Codex',false],
['Heir Apparent','human aristocrat 4','3','humanoid','any','NPC Codex',false],
['Falconer','human aristocrat 5','4','humanoid','any','NPC Codex',false],
['Officer','elf aristocrat 6','5','humanoid','any','NPC Codex',false],
['Mayor','human aristocrat 7','6','humanoid','any','NPC Codex',false],
['Diplomat','half-elf aristocrat 8','7','humanoid','any','NPC Codex',false],
['Knight','human aristocrat 9','8','humanoid','any','NPC Codex',false],
['King','human aristocrat 10','9','humanoid','any','NPC Codex',false],
['Beggar','half-elf commoner 1','-1','humanoid','any','NPC Codex',false],
['Pig Farmer','human commoner 2','0','humanoid','any','NPC Codex',false],
['Miner','dwarf commoner 3','1','humanoid','any','NPC Codex',false],
['Accomplished Angler','halfling commoner 4','2','humanoid','any','NPC Codex',false],
['Barmaid','human commoner 5','3','humanoid','any','NPC Codex',false],
['Shopkeeper','elf commoner 6','4','humanoid','any','NPC Codex',false],
['Ruffian','human commoner 7','5','humanoid','any','NPC Codex',false],
['Village Elder','half-orc commoner 8','6','humanoid','any','NPC Codex',false],
['Constable','human commoner 9','7','humanoid','any','NPC Codex',false],
['Traitor','human commoner 10','8','humanoid','any','NPC Codex',false],
['Apprentice Jeweler','human expert 1','0','humanoid','any','NPC Codex',false],
['Old Sailor','elf expert 2','1','humanoid','any','NPC Codex',false],
['Seasoned Trapper','halfling expert 3','2','humanoid','any','NPC Codex',false],
['Journeyman Carpenter','half-orc expert 4','3','humanoid','any','NPC Codex',false],
['Sapper','human expert 5','4','humanoid','any','NPC Codex',false],
['Expert Blacksmith','dwarf expert 6','5','humanoid','any','NPC Codex',false],
['Successful Merchant','human expert 7','6','humanoid','any','NPC Codex',false],
['Wise Sage','human expert 8','7','humanoid','any','NPC Codex',false],
['Cutthroat Lawyer','half-elf expert 9','8','humanoid','any','NPC Codex',false],
['Master Entertainer','gnome expert 10','9','humanoid','any','NPC Codex',false],
['Recruit','dwarf warrior 1','0','humanoid','any','NPC Codex',false],
['Brigand','human warrior 2','1','humanoid','any','NPC Codex',false],
['Guard','human warrior 3','2','humanoid','any','NPC Codex',false],
['Veteran Buccaneer','human warrior 4','3','humanoid','any','NPC Codex',false],
['Tavern Champoin','half-orc warrior 5','4','humanoid','any','NPC Codex',false],
['Grizzled Mercenary','human warrior 6','5','humanoid','any','NPC Codex',false],
['Expert Bodyguard','human warrior 7','6','humanoid','any','NPC Codex',false],
['Aloof Archer','elf warrior 8','7','humanoid','any','NPC Codex',false],
['Cavalry Soldier','half-elf warrior 9','8','humanoid','any','NPC Codex',false],
['Gladiator Champion','human warrior 10','9','humanoid','any','NPC Codex',false],
['Amiri','human barbarian 1','1','humanoid','any','NPC Codex',true],
['Amiri','human barbarian 7','7','humanoid','any','NPC Codex',true],
['Amiri','human barbarian 12','12','humanoid','any','NPC Codex',true],
['Lem','halfling bard 1','1','humanoid','any','NPC Codex',true],
['Lem','halfling bard 7','7','humanoid','any','NPC Codex',true],
['Lem','halfling bard 12','12','humanoid','any','NPC Codex',true],
['Kyra','human cleric of sarenrae 1','1','humanoid','any','NPC Codex',true],
['Kyra','human cleric of sarenrae 7','7','humanoid','any','NPC Codex',true],
['Kyra','human cleric of sarenrae 12','12','humanoid','any','NPC Codex',true],
['Lini','gnome druid 1','1','humanoid','any','NPC Codex',true],
['Lini','gnome druid 7','7','humanoid','any','NPC Codex',true],
['Lini','gnome druid 12','12','humanoid','any','NPC Codex',true],
['Valeros','human fighter 1','1','humanoid','any','NPC Codex',true],
['Valeros','human fighter 7','7','humanoid','any','NPC Codex',true],
['Valeros','human fighter 12','12','humanoid','any','NPC Codex',true],
['Sajan','human monk 1','1','humanoid','any','NPC Codex',true],
['Sajan','human monk 7','7','humanoid','any','NPC Codex',true],
['Sajan','human monk 12','12','humanoid','any','NPC Codex',true],
['Seelah','human paladin of iomedae 1','1','humanoid','any','NPC Codex',true],
['Seelah','human paladin of iomedae 7','7','humanoid','any','NPC Codex',true],
['Seelah','human paladin of iomedae 12','12','humanoid','any','NPC Codex',true],
['Harsk','dwarf ranger 1','1','humanoid','any','NPC Codex',true],
['Harsk','dwarf ranger 7','7','humanoid','any','NPC Codex',true],
['Harsk','dwarf ranger 12','12','humanoid','any','NPC Codex',true],
['Merisiel','elf rogue 1','1','humanoid','any','NPC Codex',true],
['Merisiel','elf rogue 7','7','humanoid','any','NPC Codex',true],
['Merisiel','elf rogue 12','12','humanoid','any','NPC Codex',true],
['Seoni','human sorcerer 1','1','humanoid','any','NPC Codex',true],
['Seoni','human sorcerer 7','7','humanoid','any','NPC Codex',true],
['Seoni','human sorcerer 12','12','humanoid','any','NPC Codex',true],
['Ezren','human wizard 1','1','humanoid','any','NPC Codex',true],
['Ezren','human wizard 7','7','humanoid','any','NPC Codex',true],
['Ezren','human wizard 12','12','humanoid','any','NPC Codex',true]
];
