//Name|Class|CR|Type|Terrain|Book/Page|isUnique
// 0 	== 1/2 CR
// -1 	== 1/3 CR
// -2	== 1/4 CR
// -3	== 1/6 CR
// -4	== 1/8 CR

var villaincodex = [
['Corrupt Scrivener','half-orc diviner 9','8','humanoid','any','Villain Codex',false],
['Wicked Orator','human bard 11','10','humanoid','any','Villain Codex',false],
['Spellmaster','human magus 12','11','humanoid','any','Villain Codex',false],
['First Advisor','halfling witch 13','12','humanoid','any','Villain Codex',false],
['High Enchanter','half-elf enchanter 13','12','humanoid','any','Villain Codex',false],
['Grand Caller','human conjurer 15','14','humanoid','any','Villain Codex',false],
['The Eminent Spellqueen','human lich sorcerer','14','undead','any','Villain Codex',true],
['Beater','human rogue (thug) 3','2','humanoid','any','Villain Codex',false],
['Enchantress','gnome sorcerer 3','2','humanoid','any','Villain Codex',false],
['Sadistic Healer','dwarf cleric 4','3','humanoid','any','Villain Codex',false],
['Sentinel','half-orc monk 4','3','humanoid','any','Villain Codex',false],
['Tactician','human cavalier 5','4','humanoid','any','Villain Codex',false],
['Guide','human ranger (guide) 7','6','humanoid','any','Villain Codex',false],
['Slaver Captain','elf swashbuckler 7','6','humanoid','any','Villain Codex',false],
['Bludgeoner','hobgoblin fighter 5','4','humanoid','any','Villain Codex',false],
['Crusher','orc barbarian 8','7','humanoid','any','Villain Codex',false],
['Experimenter','human alchemist (vivisectionist 6','5','humanoid','any','Villain Codex',false],
['Slave Master','human bard (court bard) 9','8','humanoid','any','Villain Codex',false],
['Roustabout','expert 3/warrior 3','4','humanoid','any','Villain Codex',false],
['Strongwoman','fighter 9','8','humanoid','any','Villain Codex',false],
['Geek','human ogrekin barbarian 4','4','humanoid','any','Villain Codex',false],
['Firebreather','human pyrokineticist 7','6','humanoid','any','Villain Codex',false],
['Acrobat','human rogue (acrobat) 6','5','humanoid','any','Villain Codex',false],
['Clown','human slayer 8','7','humanoid','any','Villain Codex',false],
['Fortune-Teller','half-elf bard (fortune-teller) 8','7','humanoid','any','Villain Codex',false],
['Beast Trainer','human ranger 9','8','humanoid','any','Villain Codex',false],
['Stagecrafter','human illusionist 10','9','humanoid','any','Villain Codex',false],
['Ringmaster','human mesmeist 11','10','humanoid','any','Villain Codex',false],
['Guard Spotter','half-elf fighter 2','1','humanoid','urban','Villain Codex',false],
['Guard Sniper','human ranger 3','2','humanoid','urban','Villain Codex',false],
['Shield Warden','dwarf fighter (shielded fighter) 3','2','humanoid','urban','Villain Codex',false],
['Guard Mage','human conjurer 4','3','humanoid','urban','Villain Codex',false],
['Misguided Paladin','human paladin 3','2','humanoid','urban','Villain Codex',false],
['Reformed Criminal','human rogue 4','3','humanoid','urban','Villain Codex',false],
['Guard Healer','human cleric 2','1','humanoid','urban','Villain Codex',false],
['Interrogator','human inquisitor 5','4','humanoid','urban','Villain Codex',false],
['Persuader','human bard 4','3','humanoid','urban','Villain Codex',false],
['Jailor','human fighter 5','4','humanoid','urban','Villain Codex',false],
['Chief Detective','human investigator 6','5','humanoid','urban','Villain Codex',false],
['Guard Captain','human vigilante 7','6','humanoid','any','Villain Codex',false],
['Oddfellow','half-orc fighter 3','2','humanoid','any','Villain Codex',false],
['Little Devil','halfling gunslinger 5','4','humanoid','any','Villain Codex',false],
['Pistoleer','human swashbuckler (picaroon) 4','3','humanoid','any','Villain Codex',false],
['Sneak Shot','half-elf rogue 5','4','humanoid','any','Villain Codex',false],
['Holy Shooter','human inquisitor 5','4','humanoid','any','Villain Codex',false],
['Arcane Musketeer','elf wizard (spellsinger) 6','5','humanoid','any','Villain Codex',false],
['Dragoon Marshal','dwarf fighter (tactician) 6','5','humanoid','any','Villain Codex',false],
['Black-Powder Sage','human investigator (steel hound) 7','6','humanoid','any','Villain Codex',false],
['Bold Captain','gnome swashbuckler (mouser, musketeer) 7','6','humanoid','any','Villain Codex',false],
['Grim Captain','human gunslinger (musket master) 8','7','humanoid','any','Villain Codex',false],
['Baroness','half-elf magus 8','7','humanoid','any','Villain Codex',false],
['Lord Marshal','human cavalier (musketeer) 9','8','humanoid','any','Villain Codex',false],
['Silent Needle','human rogue 5','4','humanoid','any','Villain Codex',false],
['Ascetic Acolyte','half-elf monk 6','5','humanoid','any','Villain Codex',false],
['Bone Bastion','human fighter (phalanx soldier) 6','5','humanoid','any','Villain Codex',false],
['Plague Angel','human antipaladin 8','7','humanoid','any','Villain Codex',false],
['Awakend Voice','human cleric 6','5','humanoid','any','Villain Codex',false],
['Death Chanter','human necromancer 7','6','humanoid','any','Villain Codex',false],
['Fevered Ravener','ghast slayer 4','6','undead','any','Villain Codex',false],
['Pestilent Messenger','pallid vector advanced minotaur','7','monstrous humanoid','any','Villain Codex',false],
['Plaguebrewer','half-orc necromancer 10','9','humanoid','any','Villain Codex',false],
['Undead Apostle','dwarf graveknight fighter (two-handed fighter) 8','9','undead','any','Villain Codex',false],
['The Reaper','human ghost cleric 9','10','undead','any','Villain Codex',true],
['Schir Inductee','human fighter 9','8','humanoid','any','Villain Codex',false],
['Abrikandilu Sunderer','dwarf barbarian (breaker) 11','10','humanoid','any','Villain Codex',false],
['Babau Poisoner','human slayer 9','8','humanoid','any','Villain Codex',false],
['Nabasu Tracker','human ranger 12','11','humanoid','any','Villain Codex',false],
['Babau Murderer','human rogue (knife master) 10','9','humanoid','any','Villain Codex',false],
['Shadowcaster','human illusionist 13','12','humanoid','any','Villain Codex',false],
['Marilith Whirlwind','elf fighter 12','11','humanoid','any','Villain Codex',false],
['Glabrezu Outsider','human cavalier 14','13','humanoid','any','Villain Codex',false],
['Vrock Ritualist','half-orc cleric 14','13','humanoid','any','Villain Codex',false],
['Succubus Recruiter','human skald 11','10','humanoid','any','Villain Codex',false],
['Merciless Balor','human antipaladin 15','14','humanoid','any','Villain Codex',false],
['Diabolist','tiefling sorcerer 7','6','outsider','any','Villain Codex',false],
['Hellguard','human anitpaladin (tyrant) 7','6','humanoid','any','Villain Codex',false],
['Infiltrator','half-elf inquisitor (infiltrator) 8','7','humanoid','any','Villain Codex',false],
['Martinet','human monk (hellcat) 8','7','humanoid','any','Villain Codex',false],
['Hellpriest','human warpriest 9','8','humanoid','any','Villain Codex',false],
['Firebrand','half-elf bard (demagogue) 10','9','humanoid','any','Villain Codex',false],
['Eliminator','human slayer 10','9','humanoid','any','Villain Codex',false],
['Infernalist','human cleric 11','10','humanoid','any','Villain Codex',false],
['Knight Tyrant','human antipaladin (tyrant) 12','11','humanoid','any','Villain Codex',false],
['Grand Inquisitor','human inquisitor (sanctified slayer) 12','11','humanoid','any','Villain Codex',false],
['Hierarch','human cleric 13','12','humanoid','any','Villain Codex',false],
['Fang Monastery Enforcer','human brawler (snakebite striker) 7','6','humanoid','any','Villain Codex',false],
['Fang Monastery Warden','human fighter 9','8','humanoid','any','Villain Codex',false],
['Fang Monastery Infiltrator','human monk 7','6','humanoid','any','Villain Codex',false],
['Fang Monastery Assassin','half-orc ninja (hunting serpent) 8','7','humanoid','any','Villain Codex',false],
['Fang Monastery Sniper','human monk (zen archer) 10','9','humanoid','any','Villain Codex',false],
['Fang Monastery Shadow','human ninja 11','10','humanoid','any','Villain Codex',false],
['Fang Monastery Mystic','human monk (qinggong monk) 9','8','humanoid','any','Villain Codex',false],
['Fang Monastery Ascendant','human sorcerer 11','10','humanoid','any','Villain Codex',false],
['Fang Monastery Master','human monk (sensei) 11','10','humanoid','any','Villain Codex',false],
['The First Fang','human oracle 12','11','humanoid','any','Villain Codex',true],
['Common Swindler','human rogue 2','1','humanoid','any','Villain Codex',false],
['Snake-Oil Seller','human cleric 3/rogue 1','3','humanoid','any','Villain Codex',false],
['Shoddy Artisan','dwarf rogue 2','1','humanoid','any','Villain Codex',false],
['Crooked Retailer','human fighter 4','3','humanoid','any','Villain Codex',false],
['Petty Fence','human rogue 3','2','humanoid','any','Villain Codex',false],
['Contraband Smuggler','halfling rogue 5','4','humanoid','any','Villain Codex',false],
['Ruthless Moneylender','human illusionist 3','2','humanoid','any','Villain Codex',false],
['Corrupt Guild Member','half-elf rogue 5','4','humanoid','any','Villain Codex',false],
['Security Manager','human fighter 6','5','humanoid','any','Villain Codex',false],
['Face','elf bard 6','5','humanoid','any','Villain Codex',false],
['Caravan Master','human rogue (charlatan) 7','6','humanoid','any','Villain Codex',false],
['Merry Minstrel','half-elf bard 2','1','humanoid','any','Villain Codex',false],
['Halfling Impostor','halfling swashbuckler (daring infiltrator) 5','4','humanoid','any','Villain Codex',false],
['Woodsmand Outlaw','human hunter 3','2','humanoid','any','Villain Codex',false],
['Deserter','human fighter 4','3','humanoid','any','Villain Codex',false],
['Ambushing Brigand','human rogue 2','1','humanoid','any','Villain Codex',false],
['Outlaw Archer','human fighter 3','2','humanoid','any','Villain Codex',false],
['Halfling Filcher','halfling rogue (filcher) 4','3','humanoid','any','Villain Codex',false],
['Elite Marauder','human ranger 5','4','humanoid','any','Villain Codex',false],
['Outlaw Lieutenant','human ranger 6','5','humanoid','any','Villain Codex',false],
['Rebel Friar','half-orc cleric (separatist) 6','5','humanoid','any','Villain Codex',false],
['The Hood','human ranger (hooded champion, skirmisher) 7','6','humanoid','any','Villain Codex',true],
['Human Hunter','human ranger 6','5','humanoid','any','Villain Codex',false],
['Wild Rager','half-orc barbarian 7','6','humanoid','any','Villain Codex',false],
['Wildfire','human druid (nature fang) 5','4','humanoid','any','Villain Codex',false],
['Immolator','human witch 6','5','humanoid','any','Villain Codex',false],
['Renewer','human shaman 8','7','humanoid','any','Villain Codex',false],
['Tracker','elf hunter 7','6','humanoid','any','Villain Codex',false],
['Wrathbringer','fungus leshy skald 7','8','plant','any','Villain Codex',false],
['Bog\'s Embrace','bog nixie sorcerer 8','10','fey','any','Villain Codex',false],
['Blight Caller','human druid (blight druid) 11','10','humanoid','any','Villain Codex',false],
['Crafty Courtier','half-elf bard 8','7','humanoid','any','Villain Codex',false],
['Royal Guard','human fighter 9','8','humanoid','any','Villain Codex',false],
['Captain of the Royal Guard','half-orc ranger (skimisher) 11','10','humanoid','any','Villain Codex',false],
['Petitioning Paladin','human paladin (divine defender) 10','9','humanoid','any','Villain Codex',false],
['Elven Spy','elf ninja 11','10','humanoid','any','Villain Codex',false],
['Prince','human fighter 7/rogue 4','10','humanoid','any','Villain Codex',false],
['Queen\'s Champion','dwarf fighter (unbreakable) 12','11','humanoid','any','Villain Codex',false],
['Vizier','human mesmeist (vizier) 13','12','humanoid','any','Villain Codex',false],
['King','human rogue (rake) 14','13','humanoid','any','Villain Codex',false],
['Queen','human witch (mirror witch) 15','14','humanoid','any','Villain Codex',false],
['Crusty Cook','human fighter 2/rogue 1','2','humanoid','any','Villain Codex',false],
['Cunning Quartermaster','human rogue 4','3','humanoid','any','Villain Codex',false],
['Witty Jury-Rigger','human investigator (empiricist) 2','1','humanoid','any','Villain Codex',false],
['Bombastic Engineer','dwarf fighter 4','3','humanoid','any','Villain Codex',false],
['Seasoned Forager','human hunter 3','2','humanoid','any','Villain Codex',false],
['Bawdy Joker','human bard 3','2','humanoid','any','Villain Codex',false],
['Grizzled Healer','human warpriest 5','4','humanoid','any','Villain Codex',false],
['Harsh Lieutenant','human fighter (tactician) 6','5','humanoid','any','Villain Codex',false],
['Arcane Artillerist','halfling evoker 6','5','humanoid','any','Villain Codex',false],
['Mercenary Captain','human fighter (seasoned commander) 7','6','humanoid','any','Villain Codex',false],
['Frenzied Cutter','human barbarian (savage barbarian) 3','2','humanoid','any','Villain Codex',false],
['War Strider','human ranger 6','5','humanoid','any','Villain Codex',false],
['Brutal Hurler','human barbarian 4','3','humanoid','any','Villain Codex',false],
['Wolf Arrow','half-elf ranger 6','5','humanoid','any','Villain Codex',false],
['War Singer','human skald 4','3','humanoid','any','Villain Codex',false],
['Rage Mage','human sorcerer 7','6','humanoid','any','Villain Codex',false],
['Spiked Charger','human barbarian 2/cavalier 4','5','humanoid','any','Villain Codex',false],
['Fiend-Born Rager','half-orc bloodrager (untouchabke rager) 8','7','humanoid','any','Villain Codex',false],
['Mad Seeress','human skald (spell warrior) 8','7','humanoid','any','Villain Codex',false],
['Crimson Lord','human shaman 9','8','humanoid','any','Villain Codex',false],
['Pirate Thug','human fighter 5','4','humanoid','any','Villain Codex',false],
['Drunken Brute','human barbarian 2/brawler 5','6','humanoid','any','Villain Codex',false],
['Tengu Sneak','tengu rogue 5','4','humanoid','any','Villain Codex',false],
['Swift-Talking Scoundrel','human bard (daredevil) 7','6','humanoid','any','Villain Codex',false],
['Swaggering Shot','human gunslinger (pistolero) 6','5','humanoid','any','Villain Codex',false],
['Musket Marauder','human rogue 8','7','humanoid','any','Villain Codex',false],
['Sea Witch','human witch (sea witch) 8','7','humanoid','any','Villain Codex',false],
['Ship\'s Surgeon','human alchemist (vivisectionist) 9','8','humanoid','any','Villain Codex',false],
['Daring Captain','human ranger 9','8','humanoid','any','Villain Codex',false],
['Ghost Captain','human ghost psychic 8','9','undead','any','Villain Codex',false],
['Vile Admiral','human swashbuckler (picaroon) 11','10','humanoid','any','Villain Codex',false],
['Channeler','human medium (relic channeler) 7','6','humanoid','any','Villain Codex',false],
['Bearer','human occultist 8','7','humanoid','any','Villain Codex',false],
['Caller','half-elf arcanist (occultist) 10','9','humanoid','any','Villain Codex',false],
['High Sire','half-elf summoner 12','11','humanoid','any','Villain Codex',false],
['High Talon','human mesmeist 13','12','humanoid','any','Villain Codex',false],
['Grand Dam','human spiritualist (haunted) 13','12','humanoid','any','Villain Codex',false],
['Cult Recruiter','human bard 9','8','humanoid','any','Villain Codex',false],
['Cult Acquistionist','human rogue 11','10','humanoid','any','Villain Codex',false],
['Cult Thug','human rogue (thug) 10','9','humanoid','any','Villain Codex',false],
['Cult Assassin','half-elf slayer 12','11','humanoid','any','Villain Codex',false],
['Cult Mystic','human medium (voice of the void) 11','10','humanoid','any','Villain Codex',false],
['Cult Cell Leader','human ranger (urban ranger) 12','11','humanoid','any','Villain Codex',false],
['Cult Librarian','half-elf occultist 10','9','humanoid','any','Villain Codex',false],
['Insane Prophet','human oracle 14','13','humanoid','any','Villain Codex',false],
['Daemonic Agent','human cleric 14','13','humanoid','any','Villain Codex',false],
['Sinister Mastermind','human mesmeist (cult master) 15','14','humanoid','any','Villain Codex',false],
['Sharpshooter','human slayer (sniper) 7','6','humanoid','any','Villain Codex',false],
['Deadeye','human ninja 9','8','humanoid','any','Villain Codex',false],
['Murderer','human alchemist 7','6','humanoid','any','Villain Codex',false],
['Rutterkin','halfling rogue (poisoner) 8','7','humanoid','any','Villain Codex',false],
['Skulk','half-orc rogue (skulking slayer) 11','10','humanoid','any','Villain Codex',false],
['Butcher','human slayer 9','8','humanoid','any','Villain Codex',false],
['Operative','human witch 10','9','humanoid','any','Villain Codex',false],
['Zen Assassin','human monk (zen archer) 6/ninja 6','11','humanoid','any','Villain Codex',false],
['Deadly Courtesan','vishkanya rogue (deadly courtesan) 12','11','humanoid','any','Villain Codex',false],
['Grandmother of Slayers','half-elf slayer 7/warpriest (cult leader) 6','12','humanoid','any','Villain Codex',false],
['Guttersnipe','halfling rogue (cutpurse) 3','2','humanoid','any','Villain Codex',false],
['Street-Corner Punk','human rogue 5','4','humanoid','any','Villain Codex',false],
['Wiseguy','human fighter 3','2','humanoid','any','Villain Codex',false],
['Gambler','human rogue 5','4','humanoid','any','Villain Codex',false],
['Second-Story Thief','half-elf rogue (heister) 4','3','humanoid','any','Villain Codex',false],
['Safecracker','human alchemist (vaultbreaker) 6','5','humanoid','any','Villain Codex',false],
['Sleuth','human rogue (snoop) 4','3','humanoid','any','Villain Codex',false],
['Mole','human bard 6','5','humanoid','any','Villain Codex',false],
['Master Spy','human rogue (spy) 7','6','humanoid','any','Villain Codex',false],
['Chemist','dwarf alchemist 8','7','humanoid','any','Villain Codex',false],
['Guildmaster','human rogue (chameleon) 9','8','humanoid','any','Villain Codex',true]
];